### ISSUE TITLE
Bug: Content-Disposition Header Lacking "filename" When "filename*" Is Present

### ISSUE THREAD

**Issue by kennytrytek-wf** [urllib3/urllib3#1062]
#### Description:
When sending files to a server that does not understand "filename*" parameters inside the Content-Disposition header, the server will fail to find the file name because the "filename" parameter is not also included.

#### Justification:
According to [RFC 6266](https://tools.ietf.org/html/rfc6266#appendix-D), ideal header generators will include both a "filename" and a "filename*" parameter whenever the "filename*" form is required:
> – Include a "filename*" parameter where the desired filename cannot be expressed faithfully using the "filename" form.  Note that legacy user agents will not process this, and will fall back to using the "filename" parameter's content.
>
> – When a "filename*" parameter is sent, to also generate a "filename" parameter as a fallback for user agents that do not support the "filename*" form, if possible.  This can be done by substituting characters with US-ASCII sequences (e.g., Unicode character point U+00E4 (LATIN SMALL LETTER A WITH DIARESIS) by "ae").  Note that this may not be possible in some locales.
>
> – When a "filename" parameter is included as a fallback (as per above), "filename" should occur first, due to parsing problems in some existing implementations.

#### Why I Care:
This inconsistency caused a many-hour debugging session when trying to discover why file uploads to Google AppEngine blobstore stopped working when the requests library was upgraded (which bundles urllib3 with install). The eventual resolution was to urlencode the file name to a `str` before upload so that the "filename*" parameter was not added.

---

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39703440-bug-content-disposition-header-lacking-filename-when-filename-is-present?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F192525&utm_medium=issues&utm_source=github).

**Comment by Lukasa** [comment]
So, we could definitely do this: we could aim to do so by encoding using an 'ignore' or 'replace' mode on the encoder. Alternatively, we could punycode.

I don't consider this enormously high priority because servers really *should* tolerate the `*` form. That means that I don't think this is going to bump any of my other work down, so anyone else who wants to is welcome to work on this.

**Comment by sprat** [comment]
Please note that `cgi.FieldStorage` don't support `filename*` form (in Python 2 at least), so all servers using the standard library's `cgi` module are actually broken. It's a bit annoying!

**Comment by sigmavirus24** [comment]
@sprat Pull requests to rectify this would be happily reviewed and accepted. Complaining gets us nowhere. Feel free to send a pull request to fix this.

**Comment by davidism** [comment]
Started doing some research. Created a Werkzeug application to echo the submitted `Content-Disposition` header.

```python
import werkzeug

form_html = """\
<form method=post enctype=multipart/form-data>
<input type=file name=file />
<input type=submit>
</form>
"""


@werkzeug.Request.application
def app(request: werkzeug.Request):
    if request.method == "POST":
        print(request.files["file"].headers["Content-Disposition"])
        return werkzeug.Response(status=204)

    return werkzeug.Response(form_html, content_type="text/html")


werkzeug.run_simple("localhost", 5000, app)
```

When a file named "basic.txt" is submitted from Firefox or Chromium, it prints:

```
form-data; name="file"; filename="basic.txt"
```

When a file named "ski ⛷️.txt" is submitted from Firefox or Chromium, it prints:

```
form-data; name="file"; filename="ski &#9975;&#65039;.txt"
```

Browsers are providing one filename, with non-ascii characters replaced with HTML character entity references.

**Comment by davidism** [comment]
Using urllib3 to upload the file, the name is not encoded.

```python
import urllib3

with open("ski ⛷.txt", "rb") as f:
    data = f.read()

http = urllib3.PoolManager()
http.request(
    "POST",
    "http://localhost:5000/",
    fields={"file": ("ski ⛷.txt", data)},
)
```

```
form-data; name="file"; filename="ski ⛷.txt"
```

**Comment by davidism** [comment]
[WHATWG HTML Standard, section 4.10.21.8, Multipart form data:](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#multipart-form-data)

> Return the byte sequence resulting from encoding the *entry list* using the rules described by RFC 7578, *Returning Values from Forms: `multipart/form-data`*

[RFC 7578, section 4.2, Content-Disposition Header Field for Each Part:](https://datatracker.ietf.org/doc/html/rfc7578#section-4.2)

> In most multipart types, the MIME header fields in each part are restricted to US-ASCII; for compatibility with those systems, file names normally visible to users MAY be encoded using the percent-encoding method in [Section 2](https://datatracker.ietf.org/doc/html/rfc7578#section-2), following how a "file:" URI \[[URI-SCHEME](https://datatracker.ietf.org/doc/html/rfc7578#ref-URI-SCHEME)\] might be encoded.
> 
> NOTE: The encoding method described in \[[RFC5987](https://datatracker.ietf.org/doc/html/rfc5987)\], which would add a "filename*" parameter to the Content-Disposition header field, MUST NOT be used.

The WHATWG HTML Standard says to follow RFC 7578 to encode `multipart/form-data`. The RFC states that *only* a `filename` key should be present, a `filename*` key is invalid. Therefore the suggestion in the original issue to send both keys is incorrect, `filename*` is only used when receiving files in a response from the server (Werkzeug's `send_file` supports this, for example).

The RFC suggests using UTF-8 percent encoding. However, browser forms are using HTML character references. I'm not clear if that's a limitation of browsers, maybe since it's HTML the filename is already HTML encoded by the time it's submitted, so it's already ASCII and doesn't get percent encoded.

**Comment by davidism** [comment]
Turns out urllib3 is already encoding values using `fields.format_header_param_html5`, which uses percent encoding, but only on control characters 0x00 - 0x1F, not arbitrary characters. It references the same multipart-form data standard above, but oddly, it says it "matches the behavior of curl and modern browsers". Not sure about curl, but browsers at least are not using percent encoding.

**Comment by davidism** [comment]
Did some more investigation and discussion on Discord.

* After adding `<meta charset=utf-8>` to the test HTML, the browser began passing through the name unchanged like curl did. Seems the a legacy behavior when no encoding is set is to using char ref replacement.
* Neither browsers nor curl do anything special with control characters, all bytes are passed through unchanged.
* urllib3 percent encodes control characters, but no other characters
* RFC 7578 says "MAY be encoded", not "MUST" be encoded

Therefore, we've concluded that current behavior of browsers/curl/urllib3 is correct, the utf-8 filename can be passed through unchanged. Even though urllib3 *could* remove the percent encoding of control characters, it will leave it for now.

**Comment by davidism** [comment]
Did more digging. #1492 https://github.com/urllib3/urllib3/pull/1492/commits/131d0d5b14aede8d061e916e765866dee9eef9e5 added the control character quoting behavior, after @sethmlarson https://github.com/urllib3/urllib3/pull/1492#discussion_r264646123 noted that the WHATWG standard said to. This was a bit confusing, since the standard no longer mentions that. I tracked that down to https://github.com/whatwg/html/pull/6282, which removed mention of escaping anything except `"` and `\` since it didn't match what clients were actually doing.

**Comment by davidism** [comment]
I think since we're at a major release point, we should consider dropping the escape character quoting to match the current standard. I can make that change, or I can change the docs only. Note that users can always provide a more constrained file name, and that servers should always be treating the given name as untrusted and do processing on it regardless of what the client sends.
