### ISSUE TITLE
AppEngineManager should provide an _original_response object.

### ISSUE THREAD

**Issue by Lukasa** [urllib3/urllib3#1193]
See the rationale on kennethreitz/requests#4044.

**Comment by cmin764** [comment]
Did someone take care of this issue above (https://github.com/requests/requests/issues/4039)? It's still present in `requests` library due to a missing attribute in urllib3 through GAE.

**Comment by sigmavirus24** [comment]
@cmin764 this issue is still open because this hasn't been fixed.

**Comment by jonparrott** [comment]
I just haven't had time to take this on as some other projects have been encroaching on my OSS time. If someone else wants to grab it before I can get to it, go ahead - I'll be happy to review the PR. :)

**Comment by rotemvilsa** [comment]
Is there anything new with that? 
I'm an AppEngine standard environment user which uses requests over multiple projects and for now 'all' I have is this patch: https://github.com/requests/requests/pull/4044/files being copied to my lib directories every time, and when I don't do that my code fails due to the cookies issue :(
I'm looking for a more stable solution, is this fix anywhere soon on your project planning?
Thanks!  :)

**Comment by cmin764** [comment]
It is still on hold and should be solved by urllib3 I guess. Anyway,  a
more stable way to do that is to make a live monkey patch into the
appengine_config.py file as in the following files:

1.
https://raw.githubusercontent.com/Skillin/skillin/master/appengine_config.py?token=AArRvV2IGFG9uD6x9W471_x9Owhx_psKks5Z3N8ywA%3D%3D
2.
https://raw.githubusercontent.com/Skillin/skillin/master/skillin/patches.py?token=AArRvXhEq6F4C1CyivmQBmjvtRUlzTFVks5Z3N-UwA%3D%3D

skillin is a package name and contains the patches.py file,  but move
things around as you want.

**Comment by erlichmen** [comment]
I just added  #1283 which suppose to handle this.

**Comment by trickidicki** [comment]
Running into this issue with current gCloud appengine SDK...

**Comment by sethmlarson** [comment]
Closed in #1283
