### ISSUE TITLE
HTTPResponse.read() closes the response causing problem with io.BufferedReader

### ISSUE THREAD

**Issue by MarSoft** [urllib3/urllib3#1305]
In the following text I mostly refer to python2 for clarity, but the problem also happens on py3.
From some library I get an active streaming `urllib3.HTTPResponse` with `preload_content=False`. That response refers to a very large CSV file, so I want to read it line-by-line passing it through `csv.reader`.
`csv.reader` requires `unicode` objects. `HTTPResponse` returns `bytes` objects, so I use `io.TextIOWrapper`. (Actually I use `backports.csv` to achieve compatibility with `io`).

Now, here is the problem:

`test.csv` - notice the last line is missing a trailing line separator:

    abc<LF>
    def

It is served with `python -m SimpleHTTPServer`.
And the test code, even without CSV:

    import io
    import urllib3

	http = urllib3.PoolManager()
	resp = http.request('GET', 'http://localhost:8000/test.csv', preload_content=False)

	for line in iter(
		io.TextIOWrapper(
			# py2's implementation of TextIOWrapper requires `read1` method which is provided by `BufferedReader` wrapper
			io.BufferedReader(
				resp
			)
		)
	):
		print(repr(line))

Here is the error:

    u'abc\n'
	Traceback (most recent call last):
	  File "test.py", line 11, in <module>
	    resp
	ValueError: I/O operation on closed file.

If I remove `TextIOWrapper` then the error is slightly different but with the same meaning:

    ValueError: readline of closed file

From what I could find out, `C` implementation of `readline` checks if the file is closed. And if (and only if) the last line is not terminated then it tries to read "the rest" which results in this error, because `HTTPResponse.read()` closes the "file" after it is finished.

This behaviour is contrary to ordinary `file` behaviour (and `io.open()` or `py3` `file` behaviour) which will not close the file on its will but instead will keep yielding empty string when trying to read past the end of file.

Which would be the best way to make streaming `HTTPResponse` work properly with `io.BufferedReader`?

**Comment by haikuginger** [comment]
Looking into this @MarSoft. Thanks for putting this in front of us.

**Comment by haikuginger** [comment]
Okay, so what we have here is an API mismatch. An HTTP response body can generally be treated as a file which...
* Is read-only
* Is not seekable
* Closes itself immediately upon reading the last byte (signaled to the `io` module via the `.closed` property)

Most of these attributes are perfectly normal and expected for a file-like object. However, self-closing is not.

|         | Behavior if read when closed | EOF behavior | Read on EOF behavior |
| - | - | - | - |
| File  | Exception | Remains open | Returns empty byte array |
| HTTP response | Returns empty byte array | Closes | Returns empty byte array |

Generally, a file is open when it can be interacted with. When it's closed, a file pointer raises exceptions when it's interacted with. Thus, we have a bit of a consistency problem. We can (and should) be able to interact with an HTTPResponse after its body has been completely read, but we're currently acting as though the file is closed immediately upon consumption.

Essentially, we're using `.closed` to telegraph that a file has been consumed, but the standard behavior for a (read-only, non-seekable) file which has been completely consumed (but which remains open) is to return an empty set of bytes. A file being closed has a semantically different meaning - it means that the file can no longer be interacted with in any way.

I propose that we change the behavior of `.close()` and `.closed` on `HTTPResponse` to more closely match the semantic meaning intended by `IOBase`. Calling `.close()` will result in a call to the underlying `httplib` response object's `.close()` method, followed by a call to `super().close()`, while `.closed` will simply inherit from `IOBase`; if the response has not been specifically closed, it will appear open - which is the more conservative move, as it will never appear _closed_ in a case where the httplib fp remains open (and therefore needs to be explicitly closed).

This table summarizes behavior before and after this change:

|                   | `close()`  | `closed` |
|-----------|-----------|----------|
|   **Before**  | Close underlying HTTP fp | Checks that underlying HTTP fp has been closed |
|   **After**   | Close underlying HTTP fp and set status to closed  | Check that status is set to closed |

@nateprewitt, you've investigated this in the past in #977. What are your thoughts? Also CC @sigmavirus24 and @Lukasa.

**Comment by SethMichaelLarson** [comment]
Lots of good information and investigation here, nice work @haikuginger. You know when tables are used in a GitHub issue comment that shit's getting serious. :)

**Comment by nateprewitt** [comment]
@haikuginger yeah, this is part of one of Python's dark rabbit holes I went down while putting together #978. I'm onboard with the proposed functionality, but I don't know if it's worth doing much before we drop Python 2. Especially since this would be a breaking change.

We currently only have a couple ways to have `closed` behave consistently between Python 2 and 3 without building out extra infrastructure. The easiest and cleanest fix going forward is probably to stop checking for `isclosed` when Python 2 support is dropped. Then we can only use the `closed` attribute in Python 3 which should do what you proposed. Otherwise, we can probably manage it ourselves, but I'm a little concerned about the `fp` getting changed underneath us. Having us maintain a `closed` property independent of the `fp` could expose us to other state issues.

----

As for @MarSoft's problem, I believe urllib3 has had this issue since `HTTPResponse` started implementing a `closed` property.

We always [force the underlying fp closed](https://github.com/shazow/urllib3/blob/master/urllib3/response.py#L385-L393) when finished reading, due to an apparent bug in Python prior to 2.7.4. This is what is causing the `BufferedReader` to break down. Until we remove that (which we would probably do when dropping 2.7 support), it's going to be a wart we'd need to code around. 

It's also probably worth noting that despite most of the IOBase classes raising a ValueError when read after `close()` is called, httplib's `HTTPResponse` continues to yield empty byte strings, so we would too.

Sorry for the scattered brain dump, trying to type it all out on mobile before bed. Happy to clarify any questions tomorrow.

**Comment by haikuginger** [comment]
> Otherwise, we can probably manage it ourselves, but I'm a little concerned about the fp getting changed underneath us. Having us maintain a closed property independent of the fp could expose us to other state issues.

@nateprewitt, understood. In general, though, since we don't ourselves rely on the property, do actively close the connection ourselves, and provide `.closed` as a convenience for compatibility with `io`, I'm leaning towards not worrying about that potential at the moment.

I'm adding two issue labels - "solution proposed" and "proposed solution accepted" and tagging this issue with the first; if there are no significant objections in the next couple days, I'll move it to the latter to indicate that any contributor or myself may begin work on the proposed change.

**Comment by gsakkis** [comment]
I also ran into this issue with the same exact use case (large csv file reading) on python 3.6. It's been 1.5 year since opened, any action planned?

**Comment by MarSoft** [comment]
Here is the workaround I used in my project:
```
class ResponseWrapper(io.IOBase):
    # This is the wrapper around urllib3.HTTPResponse
    # to work-around an issue urllib3/urllib3#1305.
    #
    # Here we decouple HTTPResponse's "closed" status from ours.
    #
    # FIXME drop this wrapper after urllib3/urllib3#1305 is fixed

    def __init__(self, resp):
        self._resp = resp

    def close(self):
        self._resp.close()
        super(ResponseWrapper, self).close()

    def readable(self):
        return True

    def read(self, amt=None):
        if self._resp.closed:
            return b''
        return self._resp.read(amt)

    def readinto(self, b):
        val = self.read(len(b))
        if not val:
            return 0
        b[:len(val)] = val
        return len(val)
```
Hope it helps :-)

**Comment by sethmlarson** [comment]
Unfortunately as noted above this would be a breaking change in terms of compatibility which we're currently not pursuing.

**Comment by gsakkis** [comment]
For anyone stumbling into this, here's a hacky temp workaround until a proper fix:
```
import io
import urllib3

http = urllib3.PoolManager()
resp = http.request('GET', 'http://localhost:8000/test.csv', preload_content=False)

# monkeypatch isclosed of the http.client.HttpResponse nested instance to return always False
resp._fp.isclosed = lambda: False                                                                                                    

for line in io.TextIOWrapper(resp):
    print(repr(line))
```

**Comment by MarSoft** [comment]
My solution is more "clean" since it won't monkey-patch anything and will never influence unrelated parts of code. But yours is more compact and might probably work a tiny bit faster since it avoids adding another wrapping later.

**Comment by gsakkis** [comment]
True, monkey patching is rarely a good idea though to be fair here the change is local; it patches a single instance, not the whole class. Here's another alternative that's between the two both in terms of intrusiveness and compactness:
```
class ExplicitlyClosedHttpResponse(urllib3.HTTPResponse):

    @property
    def closed(self):
        return self._fp.closed


http = urllib3.PoolManager()
resp = http.request('GET', 'http://localhost:8000/test.csv', preload_content=False)

# change the class from standard urllib3.HttpResponse
resp.__class__ = ExplicitlyClosedHttpResponse

for line in io.TextIOWrapper(resp):
    print(repr(line))
```

@sethmlarson how about adding an extra `autoclose` attribute, True by default for backwards compatibility, that would implement the desired behavior when False?

**Comment by sethmlarson** [comment]
So that attribute would be used like so:

```python
r = urllib3.PoolManager().request("GET", "http://google.com", preload_content=False)
r.autoclose = False
for line in io.TextIOWrapper(r):
   ...
```

I'd be open to a PR for this change. :)

**Comment by pquentin** [comment]
@sethmlarson I think this issue can be closed now that there's nothing actionable left. Do you agree?

**Comment by sethmlarson** [comment]
Agreed!
