### ISSUE TITLE
Have accept_encoding=False behave like httplib skip_accept_encoding.

### ISSUE THREAD

**Issue by GHXST01** [urllib3/urllib3#1321]
Currently when accept_encoding is set to "False" it will set it's value to 'identity'.
I'd like to be able to omit the 'accept_encoding' header entirely like the httplib module offers.

Due to project limitations I am not able to modify server behavior.
If anyone has an alternative, I'd like to hear it.

Thanks everyone for their amazing work.

**Comment by haikuginger** [comment]
I'd accept a PR to implement this. [This code block](https://github.com/shazow/urllib3/blob/d6bf2e32686954c7da7031647674ef38957f1520/urllib3/util/request.py#L48-L55) is the region that'll need modification; note that we don't seem to be setting the header ourselves if `accept_encoding` is falsey, so that might be getting set lower down in the stack.

**Comment by SethMichaelLarson** [comment]
This issue requires a bit of work. Surprisingly `Connection.request_chunked()` is actually easier to change to get this to work already, `Connection.request()` has more work to do, we'd have to override the method most likely.

Here's my thought process of how this might be implemented:
- Add a kwarg in `PoolManager.request` called `accept_encoding`, forwards the value to `ConnectionPool.urlopen`
- Add a kwarg to ConnectionPool.urlopen called `accept_encoding`, forwards to `Connection.request` and `Connection.request_chunked`
- Add `**kw` to `Connection.request` and `Connection.request_chunked`, if `False` set `skip_accept_encoding=True` before passing to httplib otherwise set the header value. (Be able to support a list of encodings or a string value like in `make_headers()`.

This seems like a lot for this small piece of functionality, unless I'm missing an easier way. :)

I don't think `make_headers` is actually used anywhere within Connection, ConnectionPool, or PoolManager. Seems to be more of a helper function?

**Comment by GHXST01** [comment]
Hey, wondering if anyone has made progress on this. I've been using PycURL for now but would obviously like this implemented into urllib3.

What dependency does urllib3 use that implements the default header values? I'll be up to take a look this coming week.

**Comment by SethMichaelLarson** [comment]
Default headers values are decided in part by urllib unfortunately (Including the `Accept` header). It'd be a lot of piping work to get this feature working in v1. See my above comment for a place to start!

**Comment by GHXST01** [comment]
Thanks for your suggestion @SethMichaelLarson . 
I'll have a look when I have more time.

Issues like these (imo) go against everything python stands for and definitely trigger me 😅 ..

Perhaps we can do something fancy as operator overloading and provide a patch meanwhile?

**Comment by cyberfox1** [comment]
What a joke.

**Comment by sethmlarson** [comment]
This can be accomplished via sending `:Accept-Encoding": urllib3.SKIP_HEADER`
