### ISSUE TITLE
Fix CI failures for macOS and Python 3.7

### ISSUE THREAD

**Issue by SethMichaelLarson** [urllib3/urllib3#1365]
Before we know it Python 3.7 will be upon us so we should work towards fixing some of these failures and moving `py37` out of the `allow_failures` list within Travis.

**Comment by crwilcox** [comment]
There was a single test failing on macOS. We were doing hard equal and failing because of `('value',) != 'value'`.

I can't identify where tests are being skipped for failure. I presume that `test_securetransport` is skipping because Secure Transport could not be imported and `test_https` was showing skipped when run with tox, but I ran though pytest directly and they all pass.

**Comment by SethMichaelLarson** [comment]
Oh okay! Would you be up to submitting a PR to take 3.7 out of the allow_failures list and fixing that test?

**Comment by crwilcox** [comment]
Sure. test fix is in PR. I just found the allow_failures setting (apparently my editor doesn't search dot-files :)). Will add a commit to the PR for that.
