### ISSUE TITLE
Retry method usage is different from definition

### ISSUE THREAD

**Issue by wenbochang** [urllib3/urllib3#1385]
Is there any reason `HTTPConnectionPool.urlopen`'s recursive calls don't use the initially defined interface?

For example in retry, urlopen is called with positional args:

```
            return self.urlopen(method, url, body, headers, retries,
                                redirect, assert_same_host,
                                timeout=timeout, pool_timeout=pool_timeout,
                                release_conn=release_conn, body_pos=body_pos,
                                **response_kw)
```

Instead of key word args:

```
            return self.urlopen(method, url, body=body, headers=headers, retries=retries,
                                redirect=redirect, assert_same_host=assert_same_host,
                                timeout=timeout, pool_timeout=pool_timeout,
                                release_conn=release_conn, body_pos=body_pos,
                                **response_kw)
```

This makes patching a bit trickier, instead of this:

```
def wrap_urlopen(func, tracing_headers):

    def urlopen(self, method, url, headers=None, **kwargs):
        headers = headers if headers else {}
        headers.update(tracing_headers)
        return func(self, method, url, headers=headers, **kwargs)

    return urlopen
```

I think the more verbose way is required:
```
def wrap_urlopen(func, tracing_headers):

    def urlopen(self, method, url, body=None, headers=None, retries=None,
                redirect=True, assert_same_host=True, timeout=None,
                pool_timeout=None, release_conn=None, chunked=False,
                body_pos=None, **response_kw):
        headers = headers if headers else {}
        headers.update(tracing_headers)
        return func(self, method, url, body=body, headers=headers,
                    retries=retries, redirect=redirect,
                    assert_same_host=assert_same_host, timeout=1,
                    pool_timeout=pool_timeout, release_conn=release_conn,
                    chunked=chunked, body_pos=body_pos, **response_kw)
    return urlopen
```

**Comment by sigmavirus24** [comment]
> Is there any reason HTTPConnectionPool.urlopen's recursive calls don't use the initially defined interface?

Can you share what you mean by "initially defined interface"?

**Comment by wenbochang** [comment]
The method definition is 2 positional args (excluding self) and rest key word args, but the retry usage is setting the key ward args as 7 positional args.

**Comment by sigmavirus24** [comment]
Ah, so I think the confusion here stems from conventions that you may be familiar with @wenbochang versus what urllib3 does. When we wrote that method definition, we weren't thinking of positional versus keyword. We wrote that before keyword-only parameters were a thing. As far as urllib3 is concerned they're defaulted parameters that do not need to always be passed. That is, more literally speaking, the way this is interpreted and used outside of urllib3 as well.

I would very much like to get onto Python 3 where we could have keyword-only arguments but that is a long way off.

I think your best path forward is to use the more verbose option because it is unlikely that all consumers of urllib3 that may be using your `wrap_urlopen`  function are going to be using those arguments as keywords exclusively.

**Comment by wenbochang** [comment]
Ah okay, thanks for taking the time to explain!
