### ISSUE TITLE
contrib/_appengine_environ.py KeyError SERVER_SOFTWARE

### ISSUE THREAD

**Issue by wittfabian** [urllib3/urllib3#1470]
https://github.com/urllib3/urllib3/blob/master/src/urllib3/contrib/_appengine_environ.py

In the development environment, the variable SERVER_SOFTWARE is sometimes not set, so the query should read as follows:

`os.environ.get('SERVER_SOFTWARE', '').startswith('Development')`

```
def is_local_appengine():
    return ('APPENGINE_RUNTIME' in os.environ and
            os.environ.get('SERVER_SOFTWARE', '').startswith('Development'))


def is_prod_appengine():
    return ('APPENGINE_RUNTIME' in os.environ and
            not os.environ.get('SERVER_SOFTWARE', '').startswith('Development') and
            not is_prod_appengine_mvms())
```

**Comment by SethMichaelLarson** [comment]
I would accept a PR that makes this change. cc: @theacodes

**Comment by theacodes** [comment]
Yeah, fine with me. I'd be curious to know when the local server doesn't set the `SERVER_SOFTWARE` and what effect that has on detection.

**Comment by wittfabian** [comment]
The Travis CI build could not complete ...

**Comment by wittfabian** [comment]
Any innovations here? @pquentin @theacodes

**Comment by zevdg** [comment]
I just ran into this bug, (simplified reproduction of how I ran into it https://repl.it/repls/ThinSpatialNumerator) and was about to submit a fix much like the two that have already been proposed.

There is some new, and possibly relevant information.  This function

```python
def is_prod_appengine_mvms():
    return os.environ.get('GAE_VM', False) == 'true'
```
seems to always returns False now.

App Engine stopped setting this variable and [removed it from their PHP docs](https://github.com/GoogleCloudPlatform/getting-started-php/pull/200/files) (I couldn't find any references to it in the python docs).

It looks like the reasons the original CL never made it in seem to be because they didn't work quite right on flex, but since the flex check isn't working anymore anyway, and no one seems to be complaining about it, I suggest we move forward with the fix now.
