### ISSUE TITLE
Should using server_hostname imply assert_hostname?

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1526]
Currently passing in `server_hostname` doesn't automatically enable hostname verification via `assert_hostname` despite `server_hostname` modifying the behavior of hostname verification if used. What are everyone's thoughts on this? cc @urllib3/maintainers

**Comment by haikuginger** [comment]
I think it's a close call. Is `server_hostname` the only path to use SNI when the network host is specified with an IP address? If so, then we definitely want to at least ensure that hostname verification can be disabled so that SNI-based routing can work when the destination server has a bad cert (which, to be clear, is Not Good, but I think our general philosophy in the past has been that we don't enforce Good Practices for people who don't want to use them).

**Comment by sethmlarson** [comment]
That's true, I think I misunderstood the conditional within `VerifiedHTTPSConnection.connect` for choosing whether we do hostname verification or not (Didn't notice that the default `assert_hostname=None` does hostname verification). Thanks for the explanation!
