### ISSUE TITLE
The library gets stuck on "Starting new HTTPS connection..."

### ISSUE THREAD

**Issue by greatvovan** [urllib3/urllib3#1535]
I am using a couple of Python packages (`wikipedia` and `mwviews` if this is important) that use `requests` package, which in turn is known to use `urllib3` under the hood. My service is issuing many requests to Wikimedia public APIs and sometimes gets stuck on getting data from the API. Enabling DEBUG logs shows the last message to be `Starting new HTTPS connection (1): en.wikipedia.org:443` which comes from `urllib3`'s connectionpool.py.

This issue occurs randomly, not depending on specific URL and succeeds on the same URL after restart. I don't know a way to intentionally reproduce the problem, it just happens randomly, may be in a day or in an hour.

A stack trace to the place where the message is being posted:

```
_new_conn, connectionpool.py:825    \
_get_conn, connectionpool.py:248     == urllib3
urlopen, connectionpool.py:588      /
send, adapters.py:449        \
send, sessions.py:646         \
request, sessions.py:533       == requests
request, api.py:60            /
get, api.py:75               /
_wiki_request, wikipedia.py:737  \
__load, wikipedia.py:336          == wikipedia
__init__, wikipedia.py:299       /
page, wikipedia.py:276          /
```

I think think that the culprit is 'urllib3' and not an other package because of following. With DEBUG logging enabled, on every successful request I see two records, both coming from `urllib3`:

```
(1) Starting new HTTPS connection (1): en.wikipedia.org:443 (connectionpool.py:812)
(2) https://en.wikipedia.org:443 "GET /w/api.php?prop=info%7Cpageprops&inprop=url&ppprop=disambiguation&redirects=&titles=Swiss+Americans&format=json&action=query HTTP/1.1" 200 272 (connectionpool.py:391)
```

When the issue occurs, the first log line is posted but the second is not, so I assume the lib sticks somewhere in between.

A Stack Overflow question and answer that seem to be relevant: https://stackoverflow.com/a/35435568/947012

In debugger session I noticed that there is no timeout parameter is being passed to requests/urllib3 functions, so I will try to patch the initial package and see if it helps. Is there any way to force some (global) timeout in urllib3 to avoid patching of the package?

What else I can do to investigate the issue? Any workarounds to try?

**Comment by haikuginger** [comment]
> In debugger session I noticed that there is no timeout parameter is being passed to requests/urllib3 functions, so I will try to patch the initial package and see if it helps. Is there any way to force some (global) timeout in urllib3 to avoid patching of the package?

This seems the likely culprit. If the caller doesn't set a timeout, after which either our connection-establishing SYN packet or the responsive SYN-ACK is dropped, then we will wait indefinitely to establish a TCP connection. This is expected behavior.

Additionally, I see from a quick perusal of the `wikipedia` code that it doesn't appear to be doing things optimally from a performance perspective. It uses `requests.get()` without establishing a `Session` object, which means that each request establishes a new session, and a new `urllib3` connection pool, before destroying it at the end of the request.

If [this](https://github.com/goldsmith/Wikipedia) is the library you're using, it doesn't appear to be in active developement, so your best bet might be to fork it and make a change to allow a timeout parameter to be passed correctly. [Here is the relevant line where a change would need to be made.](https://github.com/goldsmith/Wikipedia/blob/2065c568502b19b8634241b47fd96930d1bf948d/wikipedia/wikipedia.py#L737). Alternately, it may be best to find an alternative Wikipedia API client.

**Comment by greatvovan** [comment]
@haikuginger I understand that `wikipedia` lib is not the state of the art and thankful for the suggestion, but this issue is more about `urllib3`. If setting of timeout helps it will be just a workaround and mean that the bug is still here. I don't see any reasons for Wikimedia servers to establish connections and keep them indefinitely long. If it was true they would get all connections exhausted pretty quickly considering amount of requests per second they have.

**Comment by greatvovan** [comment]
The benefit of reusing connection is pretty clear. My point is that they will not delay writing the response to my socket by a couple of days. Because "what for?" Requests of my type usually take several milliseconds, they cannot be legitimately handled for hours on the server.

To my understanding, the nature of TCP protocol guaranties delivery of all sent packets. If something was lost in between two parties it is re-sent. I am not telling that you are wrong, you explanation just does not make sense to me.

Anyway I will post here if setting timeouts helped, I agree it is shame that authors forgot about it.

**Comment by sigmavirus24** [comment]
@greatvovan it's unlikely that urllib3 is getting stuck after opening the connection. If anything, I'd imagine that trying to start it is being hung up on finding DNS, or trying to open connections, or something going sideways in your OS while we try to create the connection. In short, there's only so much urllib3 can do and there's barely any information in here to actually point to a problem with the library
