### ISSUE TITLE
Password-protected keyfiles questions

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#1622]
Thanks to @sethmlarson, #1489 added support for password-protected client keyfiles. But to merge it into the urllib3 async branch, I need to understand how it works. :) So I have two questions.

First, do we need to add a password argument to our  own `SSLContext.load_cert_chain`? See https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/ssl_.py#L125-L127 (Also, it looks like if we require Python 2.7.9+ which is nearly 5 years old then we can stop providing our own SSLContext.)

Second, why do you need a if here? Since the default password value of None, it looks like we can inconditionally pass password in https://github.com/urllib3/urllib3/blob/master/src/urllib3/util/ssl_.py#L353-L356

Thanks!

**Comment by pquentin** [comment]
Ah, I know why the tests did not fail even if we forgot to update our own SSLContext: we run Python 2 tests using 2.7.15 on Travis and 2.7.16 on AppVeyor, and Python 3 tests use Python 3.4+. In all those versions, the standard library provides a SSLContext. So our own SSLContext is not tested at all, but we did not notice that because of the "Platform-specific: Python 2" comment.

**Comment by sethmlarson** [comment]
We don't have to add an argument as `SSLContext.load_cert_chain()` didn't support the password parameter until Python 3.3. And we can't unconditionally pass in the password otherwise versions that don't have the parameter will exception out (like in the case of Python 2.7.9). The confusing part is that because SSLContext was completely backported to Python 2.7 after it was released in Python 3 there was already a password parameter so that parameter in particular doesn't get mentioned as "added in 2.7.9".

**Comment by sethmlarson** [comment]
I think that this could all be documented a lot better though! Especially in user docs.

**Comment by pquentin** [comment]
Thank you, that makes a lot of sense!
