### ISSUE TITLE
decryption failed or bad record mac

### ISSUE THREAD

**Issue by hamid-r-shakibi** [urllib3/urllib3#1627]
Hi,
I'm using urllib3 version 1.25.3 and every time I sometimes when I try to connect to sites it gives me decryption failed or bad record mac error.
`urllib3 HTTPError [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2305)`
I tried to search in google but I didn't find anything useful.i even don't. I even tried deleting and add new SSL cert even with other cert but it doesn't work. why this error is happening and any suggestions to fix it?

**Comment by sethmlarson** [comment]
Is this a website that's publicly available? Would there be any reason that any part of your stack (network card, virtual machine, container) that your packets would be truncated or modified in any way?

**Comment by hamid-r-shakibi** [comment]
@sethmlarson Idont get.you mean someone can modify? and yes, Its publicly available

**Comment by sethmlarson** [comment]
A lot of the cases where this problem is found it's where people's packets are either being truncated, modified, or arriving out of order. Also some issues with TLSv1 vs SSLv3 but we disable both of those. If this is the case for you then that could be why you're seeing this problem.

If this website is publicly available would you mind posting the URL so I can investigate?

**Comment by hamid-r-shakibi** [comment]
@sethmlarson
sure.this is the link:
tabriztak.com
By the way it's not a english website. And I enabled ssl from sslforfree.com .

**Comment by sethmlarson** [comment]
I'm unable to reproduce your issue. You may have to investigate deeper into your specific setup as to why your TLS records are failing MAC checks.
