### ISSUE TITLE
Can't connect to IPv6 Address with Zone ID

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#1641]
From @alex-fu27 psf/requests#5126: 

Requests fails on IPv6 URLs that contain a zone identifier when used with the current urllib3 (1.25).

Expected Result
Prior to urllib3 v1.25, I could do this:

import requests
requests.get("http://[fe80::145e:58ff:fec3:4698%enp0s20u1]:8080/")
And it worked as intended.

Actual Result
Since I upgraded to urllib 1.25 and requests 2.22, this fails with [Errno -2] Name or service not known, because requests is escaping the % character and trying to access [fe80::145e:58ff:fec3:4698%25enp0s20u1] instead.

### Minimum requirements

:dollar: **You can get paid to complete this issue! [Please read the docs for more information](https://urllib3.readthedocs.io/en/latest/contributing.html#getting-paid-for-your-contributions).**

- [x] Read https://datatracker.ietf.org/doc/html/rfc4007 and https://datatracker.ietf.org/doc/html/rfc6874 to understand the feature
- [x] Research and document why urllib3<1.25 worked while urllib3>=1.25 doesn't work in this issue
- [x] Figure out the best percent encoding strategy for Python across all platforms (Linux, macOS, and Windows). You can reach out to maintainers with a script to test this on their own machine if you don't have access to a certain platform. A valid outcome of this is "we shouldn't modify the Zone ID separator" but let's test instead of assume!
- [x] Implement the feature to forward Zone ID from the authority to the `socket.create_connection` call.
- [x] Add test cases that can run on CI (might have to use mocks of `urllib3.util.connection.create_connection`?) but should have the ability to run a live test when available (figure out how to detect this situation at least on Linux)

**Comment by shamsway** [comment]
I've hit this as well

**Comment by sethmlarson** [comment]
I'm working on resolving this issue and another issue related to IPv6 Zone IDs.

**Comment by delroth** [comment]
I looked into this issue and found a few surprising things. Long story short, 1.25 broke this with 5d523706c7b03f947dc50a7e783758a2bfff0532 (#1531), but 1.25.4 accidentally (?) fixed this already with 5b047b645f5f93900d5e2fc31230848c25eb1f5f (#1647), and thus this issue report is obsolete. The breakage was actually very short lived.

However, I've still sent PR #2629 to improve the testing situation as suggested to avoid future regressions.

Feel free to adjust the bounty amount and/or retract the bounty based on this info -- while I found this issue through the bounty program (h/t @pquentin on Twitter :) ), I'm not particularly after the money.

---------

The long version, in a few bullets:

- RFC 6874 defines `http://[a::b%25iface]/` as the standard way of specifying zone IDs in URLs containing IPv6 addresses. This is against the historical precedent of simply using `http://[a::b%iface]/` which was already widely supported. As the standard explains, this syntax is incompatible with the usual URL syntax and its percent-escaping, so the newer `%25` separator is preferred. Many libraries and clients still support the non-escaped `%` zone ID separator though (including `wget`, `curl`, `aria2c`), and urllib3 should arguably continue supporting this non-standard syntax when unambiguous.

- First piece of the regression puzzle: URL host extraction was changed in 5d523706c7b03f947dc50a7e783758a2bfff0532 to use the rfc3986 library and improve URL parsing accuracy. This introduced a behavioral change regarding zone IDs. The host extractor used to not normalize the `%` separator to a (more valid, URL-wise) `%25`, but it now does.
```python
# Previous behavior
>>> urllib3.util.url.get_host('http://[a::b%iface]/')
('http', '[a::b%iface]', None)
>>> urllib3.util.url.get_host('http://[a::b%25iface]/')
('http', '[a::b%25iface]', None)

# New behavior
>>> urllib3.util.url.get_host('http://[a::b%iface]/')
('http', '[a::b%25iface]', None)
>>> urllib3.util.url.get_host('http://[a::b%25iface]/')
('http', '[a::b%25iface]', None)
```

- Second piece of the regression puzzle: URL host normalization was also changed in that same commit, also impacting zone IDs. While the previous normalization function converted `%25` into `%`, the new one doesn't. Note that due to the extraction change, the input to the normalization will always be `%25` in the new behavior:
```python
# Previous behavior
>>> urllib3.connectionpool._ipv6_host('[a::b%iface]', 'https')
'a::b%iface'
>>> urllib3.connectionpool._ipv6_host('[a::b%25iface]', 'https')
'a::b%iface'

# New behavior
>>> urllib3.connectionpool._normalize_host('[a::b%25iface]', 'https')
'a::b%25iface'
```

- Third and final piece of the regression puzzle: urllib3 doesn't really handle IPv6 zone IDs itself, but it doesn't need to -- `getaddrinfo(7)` (and thus Python's `socket.getaddrinfo`) does it fine on its own. So as long as the 'a::b%iface' host makes it to there, nothing has to be done in terms of forwarding. But since it's now `a::b%25iface` instead of `a::b%iface` as previously explained, things break. `getaddrinfo` respects RFC 4007, the `%25` thing is from RFC 6874 and specific to URLs.
```python
>>> socket.getaddrinfo('fe80::56b2:3ff:fe8d:5ac9', 80, socket.AF_INET6, socket.SOCK_STREAM)
[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::56b2:3ff:fe8d:5ac9', 80, 0, 0))]
>>> socket.getaddrinfo('fe80::56b2:3ff:fe8d:5ac9%wlp4s0', 80, socket.AF_INET6, socket.SOCK_STREAM)
[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::56b2:3ff:fe8d:5ac9', 80, 0, 3))]
>>> socket.getaddrinfo('fe80::56b2:3ff:fe8d:5ac9%lo', 80, socket.AF_INET6, socket.SOCK_STREAM)
[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::56b2:3ff:fe8d:5ac9', 80, 0, 1))]

# Note the final 0, 1, 3 in the returned sockaddr tuple -- it's the scope_id.
```

- Now, the accidental (?) fix from 5b047b645f5f93900d5e2fc31230848c25eb1f5f: `urllib3.util.url.get_host` normalizes both `%iface` and `%25iface` to `%iface`. This is IMHO the correct fix: the `%25` is an URL detail, and we shouldn't expect to get percent-encoded entities out of the URL parser.
```python
>>> urllib3.util.url.get_host('http://[a::b%iface]/')
('http', '[a::b%iface]', None)
>>> urllib3.util.url.get_host('http://[a::b%25iface]/')
('http', '[a::b%iface]', None)
```

**Comment by sethmlarson** [comment]
Thanks @delroth for all this context and investigation! I don't think we need to change the bounty amount if you're interested in being paid for the work you've done, let me know if you're interested and eligible! :)

**Comment by delroth** [comment]
I mean, I'm not going to complain :) I should be eligible. This ended up being less work than expected though, so I really wouldn't mind it moved one bucket down to $300 for fairness with other contributors.

**Comment by pquentin** [comment]
I think the system is working as intended: you tested the code, were surprised that it worked, tried various commits, made some research, took the effort to present it clearly, opened a PR, answered to comments, etc. Even with your efficiency, this is still hours of effort! And we don't want to punish contributors for being efficient.

Shut up and take our money when #2629 lands :)

**Comment by sethmlarson** [comment]
This issue has been closed in https://github.com/urllib3/urllib3/pull/2629 and and #2635. Thanks @delroth! I look forward to seeing your invoice to collect the bounty :)

**Comment by becarpenter** [comment]
I'm sorry that I only found this thread today, but FYI RFC 6874 was regretfully obsoleted by https://www.rfc-editor.org/info/rfc9844/, which you need to read to understand the background to this rather messy business. It's certainly harmless if urllib3 still supports the format, but current browsers definitely don't.
