### ISSUE TITLE
regression in urllib3 > 1.22 parsing bracketed IPvX URLs

### ISSUE THREAD

**Issue by muelli** [urllib3/urllib3#1707]
With urllib-1.22 I was able to do:
```
urllib3.util.parse_url("http://[[127.1]]")
```

With 1.24 that results in an exception:
```
/tmp/gks3/lib/python3.6/site-packages/urllib3/util/url.py in parse_url(url)
    399 
    400     except (ValueError, AttributeError):
--> 401         return six.raise_from(LocationParseError(source_url), None)
    402 
    403     # For the sake of backwards compatibility we put empty

/tmp/gks3/lib/python3.6/site-packages/urllib3/packages/six.py in raise_from(value, from_value)

LocationParseError: Failed to parse: http://[[127.1]]
```

In my usecase, I receive an IP address and I have happily added brackets to make it work with both IPv4 and IPv6 addresses. Relying on that behaviour may have been too naïve, but anyway, that behaviour is broken now.

**Comment by sethmlarson** [comment]
The behavior you're relying on is not standard (RFC 3986) and won't be supported by urllib3. You will have to update your code to use the latest urllib3.

**Comment by fruch** [comment]
Since other tools does support it, like for example curl. and urllib3 already supported it.
it a nice usability feature, that RFC3986 seems to miss. 
any examples of what wrong with supporting that ? i.e. any example of thing that might break cause of that ? (and how they are not breaking curl, as an example of a tool that does support it)
