### ISSUE TITLE
urllib3 installation requires setuptools >= 36.2.5

### ISSUE THREAD

**Issue by Johnlisk** [urllib3/urllib3#1753]
when I install urllib3 by setup.py,I got this:
```
[root@localhost urllib3]# python2 setup.py install
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
error in urllib3 setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
```
I use python==2.7.5 setuptools==41.6.0

**Comment by pquentin** [comment]
Hello @Johnlisk! I'm sorry that you had trouble installing urllib3. Thank you for 1/ reporting your problem 2/ offering a fix! This is really appreciated.

However, the current syntax is valid and means that the `ipaddress` packages should only be installed with Python 2.7 for users that use `pip install urllib3[secure]`.

`python_version=='2.7'` is an [environment marker](https://www.python.org/dev/peps/pep-0508/), and such markers are accepted in extras_requires since setuptools v36.2.5 (see https://github.com/pypa/setuptools/issues/1087 for details).

Here are a few questions to better understand your problem:

 * Are you sure you're using the latest setuptools? What is the output of `python2 -c 'import setuptools; print setuptools.__version__'`?
 * Is this the full message you get? Only mentions on distutils, no mentions of setuptools?
 * Are you on RHEL ? What version?

**Comment by Johnlisk** [comment]
that's the output, I jsut run `pip install setuptools --upgrade` to upgrade my setuptools to 41.6.0 before I run `python setup.py install`,
```
[root@localhost ~]# python2 -c 'import setuptools'
[root@localhost ~]# python2
Python 2.7.5 (default, Aug  7 2019, 00:51:29)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> print setuptools.__version__
0.9.8
>>>
```
the messages in the issue is messages all I got,nothing for setuptools
I'm on CentOS Linux release 7.6.1810 (Core)
pip version 19.1.1

**Comment by pquentin** [comment]
Thanks! So it looks like you're really using setuptools 0.9.8, not setuptools 41.6.0. I suggest you try `python2 -m pip install --upgrade setuptools` to make sure you're upgrading to the correct version. If you have further problems, please try asking your question elsewhere as issues are for bugs and new feature proposals. :)

@sethmlarson Should we try to support older setuptools versions, the same way we support older Python versions? If no, this issue can be closed.

**Comment by Johnlisk** [comment]
I tried print(setuptools.__version__) on my python3 shell and it output 41.6.0 correctly.
maybe that's a environment problem ,pip not base on my system's python environment.
I got it,thank you

**Comment by sethmlarson** [comment]
Thanks for the investigation everyone!

**Comment by heart-scalpel** [comment]
> I tried print(setuptools.**version**) on my python3 shell and it output 41.6.0 correctly.
> maybe that's a environment problem ,pip not base on my system's python environment.
> I got it,thank you

Hi,Johnlisk
How do you solve environmental problems?
I did ''cd setuptools-31.0.0 && python2 setup.py install --force"but it's not work.
what happened is "ImportError: <module 'setuptools.dist' from '/usr/lib64/python2.7/site-packages/setuptools/dist.pyc'> has no 'check_specifier' attribute".
I need your help,thanks.

**Comment by pquentin** [comment]
@heart-scalpel Sorry that you're having an issue here, but this is our issue tracker, not a support forum. Can you try asking your question elsewhere, such as StackOverflow? If it's specific to urllib3, our Discord channel is also an option.
