### ISSUE TITLE
Replace method_whitelist and DEFAULT_REDIRECT_HEADERS_BLACKLIST parameter names for the Retry method

### ISSUE THREAD

**Issue by gds-ahine** [urllib3/urllib3#1916]
Ref: https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html

Request to replace the following parameters in the `Retry` module with neutral terms that do not have any Slavery connotation.

`method_whitelist`
`DEFAULT_REDIRECT_HEADERS_BLACKLIST`

Many thanks.

**Comment by sethmlarson** [comment]
Yep, this is on my to-do list. Gotta jump through a few hoops to make it backwards compatible but also not appear in the documentation.

**Comment by antoinesouchon1982** [comment]
Black is associated with evil in many cultures simply because black is the color of darkness, and in the dark you can not see anything, you will not notice how the enemy or predator creeps up, so the darkness was associated with fear and danger. That was the reason why the expressions like black humor, black market, black metal, black sheep and black list have appeared. These expressions have been around for a long time and have nothing to do with racism or anything of that kind. 
However, in Japanese culture black is the color of age and experience, so the belt of the highest rank is black. This is just the traditions of different nations, and removing the expressions like 'black list', 'white list', etc. from the code is absolutely useless, it will not solve the problem.

**Comment by sethmlarson** [comment]
I'd already set my mind to doing this brefore this issue was raised. Unless another collaborator objects we'll be taking action.

**Comment by sigmavirus24** [comment]
I'm all for doing it
