### ISSUE TITLE
Use SSLContext from Python Library

### ISSUE THREAD

**Issue by achapkowski** [urllib3/urllib3#1995]
The `certifi` library often runs into issues with domain certificates, but in the standard `urllib.request` library has no issue. 

If I set the context to use the certifi's file, I get the SSL error, 

```python
import ssl
import certifi
import requests.urllib as urlrq

resp = urlrq.urlopen(url="https://<web address>/rest/info?f=json", 
                                  context=ssl.create_default_context(cafile=certifi.where()))
```

if I use the standard library and set the context as follows:

```python
import ssl
import certifi
import requests.urllib as urlrq

resp = urlrq.urlopen(url="https://<web address>/rest/info?f=json", 
                                  context=ssl.SSLContext(ssl.PROTOCOL_TLSv1))
```

No SSL error.

How can I get `urllib3` to honor this `SSLContext` and my OS's certificate store?

**Comment by sethmlarson** [comment]
That's because creating an `ssl.SSLContext()` on it's own like that doesn't enable verification. The website is presenting a certificate to the client but the client isn't verifying that certificate in any way (hostname or CA).

See this example with a website with a totally invalid certificate, the response comes back with no errors either (even though you'd expect there to be!)

```python
resp = urlrq.urlopen(url="https://wrong.host.badssl.com/", context=ssl.SSLContext())
```

Creating an `SSLContext` through `create_ssl_context(...)` enables verification by default which is why you're seeing errors when you use it. There's two ways to go from here:

The recommended way would be to find our why the certificate isn't verifying with certifi. Do you have the error you're receiving from urllib3?

The other route is to explicitly disable verification via `cert_reqs="CERT_NONE"`, however you're then vulnerable to many attacks and your data shouldn't be considered secure.

**Comment by sethmlarson** [comment]
Also since this isn't a defect in urllib3 I'm going to close this issue.
