### ISSUE TITLE
Refresh the ConnectionPool.urlopen docstring

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2003]
- Missing the `url` parameter from docs
- Mentions non-existing `post_url`?
- I'm sure there's more, likely good to put eyeballs on it :)

**Comment by matthewhughes934** [comment]
Hi, I'm interested in working on this.

**Comment by sethmlarson** [comment]
@matthewhughes934 Sounds good, submit a PR and I'll review

**Comment by matthewhughes934** [comment]
Sorry, managed to confuse myself and commented on + linked to #2019 instead :man_facepalming: 

Just noting: the docs didn't build for me without `pyopenssl` and `brotli` installed:

```
$ urllib3/docs$ make html
<----TRUNCATED---->
Warning, treated as error:
autodoc: failed to import module 'pyopenssl' from module 'urllib3.contrib'; the following exception was raised:
No module named 'OpenSSL'
```

```
$ urllib3/docs$ make html
<----TRUNCATED---->
Warning, treated as error:
autodoc: failed to import class 'BrotliDecoder' from module 'urllib3.response'; the following exception was raised:
Traceback (most recent call last):
```

(since `BrotliDecoder` appears to only be defined if `import brotli` doesn't raise an `ImportError`). Not convinced this wasn't just me missing something in the setup though.

**Comment by sethmlarson** [comment]
You should use `nox -s docs` to ensure your environment is consistent while building docs.
