### ISSUE TITLE
Retry + Timeout hangs when checking if container is up

### ISSUE THREAD

**Issue by abitrolly** [urllib3/urllib3#2037]
I need to check if a container is up. I created the Python script below that should timeout if no response to HEAD was received in 2 seconds. But the script hangs.

### Environment

Fedora 33.

```python
OS Linux-5.8.17-300.fc33.x86_64-x86_64-with-glibc2.32
Python 3.9.0
urllib3 1.25.8
```

### Steps to Reproduce

Run container that exposes non-listening port.
```
podman run -d -p 9990 -it bash
```

Run `time python httpcheck.py`.

```python
import requests
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
from requests.packages.urllib3.util import Timeout

with requests.Session() as s:
    retry = Retry(connect=3, backoff_factor=0.5)
    adapter = HTTPAdapter(max_retries=retry)
    s.mount('http://', adapter)
    s.mount('https://', adapter)
    s.headers['Connection'] = 'close'
    r = s.head('http://127.0.0.1:9990', timeout=Timeout(2), stream=False)
    print(r)
```

### Expected Behavior

Script timeout after 2 seconds. 

### Actual Behavior

Script hangs for 6 minutes.
```python
➜  ~ time python ~/p/scripts/httpcheck.py
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib64/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  [Previous line repeated 7 more times]
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9990): Max retries exceeded with url: / (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anatoli/p/scripts/httpcheck.py", line 16, in <module>
    r = s.head('http://127.0.0.1:9990', timeout=Timeout(2), stream=False)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 565, in head
    return self.request('HEAD', url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9990): Max retries exceeded with url: / (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
python ~/p/scripts/httpcheck.py  0.15s user 0.02s system 0% cpu 6:09.43 total
```

**Comment by sigmavirus24** [comment]
You specified a urllib3 timeout to the Requests timeout parameter which is unnecessary. You're likely doing this because you believe `total` is equivalent to "wall-clock timeout" which it is not. See

```
        This combines the connect and read timeouts into one; the read timeout
        will be set to the time leftover from the connect attempt. In the
        event that both a connect timeout and a total are specified, or a read
        timeout and a total are specified, the shorter timeout will be applied.

        Defaults to None.
```

We [clone the timeout in the ConnectionPool](https://github.com/urllib3/urllib3/blob/1a8e741996fb49074e4a32a72e8d1562a940fa38/src/urllib3/connectionpool.py#L320) used by Requests

To get a wall-clock timeout, you'll need to find a solution that works best for you (starting a thread, etc.) which this library does not provide. You would know that if you had searched closed and open issues either here or on the Requests repository

**Comment by abitrolly** [comment]
@sigmavirus24 I removed `urllib3` timeout. It didn't help. The script still hangs for 6 minutes instead of 2 seconds.

**Comment by sigmavirus24** [comment]
@abitrolly your timeout is for each retry. It's not a total across all retries. You want a wall-clock timeout which urllib3 does not and will not provide.

**Comment by abitrolly** [comment]
@sigmavirus24 not sure why I need wall-clock. Why a network timeout is not possible?

**Comment by sigmavirus24** [comment]
You've configured retries which means that the timeout you've is cloned for each attempt. You want everything to timeout after 2 seconds, but a timeout triggers a retry. You said you want the whole thing to timeout after 2 seconds - that's a wall-clock timeout (user-perceived time). What you've configured will never achieve that. That's why you want a wall-clock timeout. Also, it seems like you're doing no research here so I'm not going to continue trying to educate you as I can't afford to spend time individually educating every single person. Please do research on your own

**Comment by abitrolly** [comment]
The timeout for each attempt is **2 seconds**, which for 3 retries should result in 6 seconds (or 6+12+24 = 42 seconds with backoff factor 0.5 if I understand it correctly). It could understand if the timeout was after 2 seconds, 6 or 42, but the code **timeouts after 6 minutes** and 9 seconds. I appreciate your attempts to educate me, but they just don't explain anything about that.

**Comment by pquentin** [comment]
Please read the Timeout docs at https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.Timeout, especially the note that starts with "Many factors can affect the total amount of time for urllib3 to return an HTTP response.".

This issue tracker is about issues in urllib3, this does not appear to be one.

**Comment by abitrolly** [comment]
@pquentin thanks for the link. I expected `urllib3` to wrap the low level details. Looks like it is impossible, and there is still no clear explanation why. The "many factors" note states these possible reasons for the bug I am experiencing.

> Python’s DNS resolver does not obey the timeout specified on the socket.

Not the case. I am using 127.0.0.1 so it should not be involved.

> high CPU load, high swap, the program running at a low priority level

Not the case. The system has a plenty of resources available to complete SYN/ACK in under 6 minutes.

![image](https://user-images.githubusercontent.com/8781107/98508429-84862f00-2270-11eb-8757-6eb945d5cd1d.png)

> if a server streams one byte every fifteen seconds, a timeout of 20 seconds will not trigger

Not the case. I tried even to check this by code, but this is a HEAD request.

So, what is going on here?

**Comment by sigmavirus24** [comment]
@abitrolly Many servers that are poorly implemented do in fact send data on HEAD requests because they translate a HEAD to a GET. `urllib3` does not treat these requests differently from a semantic point of view so if the server is sending data, urllib3 will try to read it (and the same goes for Requests). You stating something is not the case doesn't make it so. Also if you attempt to say "CURL doesn't do this" I'll point out that CURL is a much different product that tracks methods and will just close the socket on the server when it disobeys the specification. So yes, CURL might not have the same problem here but that's not the bug.

The bug is you want a total user time of 2s and urllib3 and requests cannot provide that to you given the variety of systems they support. Neither threading nor multiprocessing are available on every system (and in some cases neither are available) and thus we can not provide a wall-clock timeout for you. You must implement that.

**Comment by abitrolly** [comment]
@sigmavirus24 your argument about HEAD doesn't apply to this.
```
podman run -d -p 9990 -it bash
```
The port is open, but there are no server to reply at all. You keep pushing the argument `if you want 2s accuracy, get yourself a wall-clock`, and I am keep telling you that **if timeout, which is set to be around 2s, takes 6 minutes, then it doesn't work, no matter of accuracy**.
