### ISSUE TITLE
Standardize HTTPResponse.read(X) behavior regardless of compression

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2128]
Currently calls to `HTTPResponse.read()` with a specified amount can vary in size depending on HTTP compression. This makes using `HTTPResponse` with other `io` primitives like `io.BufferedReader()` difficult as they assume `.read(X)` won't return more bytes than `X`.

Related issue: https://github.com/urllib3/urllib3/issues/709

### Minimum requirements

:dollar: **You can get paid to complete this issue! [Please read the docs for more information](https://urllib3.readthedocs.io/en/latest/contributing.html#getting-paid-for-your-contributions).**

- [ ] Calling `HTTPResponse.read(x)` should result in the same behavior regardless of whether the response is compressed or not.
- [ ] Test cases for `decode_content=True/False`, `MultiDecoder` (more than one `Content-Encoding`), all the different Content-Encodings and `identity`. Test when `.stream()`-ing from the `HTTPResponse` or in manual `.read()`.
- [ ] May need to buffer output across calls to `.read()` and `decompress` until there's at least `n` bytes available to be read.

**Comment by sigmavirus24** [comment]
Part of me genuinely wonders if we need a separate collaborator that wraps an `HTTPResponse` to do the decoding, rather than having the `HTTPResponse` do it for us. I'm thinking along the lines of if someone gives us `decode_content=True` it returns a `DecodedHTTPResponse` which has the original and does the buffer magic for us to ensure we don't return more than `N` and don't lose data in the interim.

**Comment by sethmlarson** [comment]
Certainly could work! Are there many users of decode_content=False? I can only remember seeing pip use that.

**Comment by sigmavirus24** [comment]
Betamax uses it to preserve the exact body bytes while recording  interactions (request-response). I think openstack/glance used it a bunch as they were moving around compressed data they didn't want uncompressed. I don't think it's a frequent use-case but I do think it's worth supporting and branching logic in `read()` or elsewhere could get very tricky

**Comment by sigmavirus24** [comment]
The other thing we could do is unconditionally read into a `BytesIO` buffer and store the content twice, but that seems undesirable. Also managing that memory effectively isn't the most easy to understand. We could use a ring-buffer here since we don't care about overwriting old-data and probably don't want to have a copy of the data in memory for the user (that's Requests' job) ;)

**Comment by baverman** [comment]
> May need to buffer output across calls to .read() and decompress until there's at least n bytes available to be read
Does it really need to return at least n bytes? Or use a more usual socket behavior: return at least 1 byte?
