### ISSUE TITLE
303 request contain original payload

### ISSUE THREAD

**Issue by mjmcconnell** [urllib3/urllib3#2131]
### Subject

As per the RFC, GET requests are not expected to contain a payload.

> A payload within a GET request message has no defined semantics;
sending a payload body on a GET request might cause some existing
implementations to reject the request

I suggest the logic for handling 303 redirects (https://github.com/urllib3/urllib3/blob/master/src/urllib3/connectionpool.py#L755) be updated, so that all requests are checked for 303 status code, and the body is explicitly dropped before sending the follow up request.

Currently this issue prevents using 303 redirects with the Google Load Balancer, as it rejects the request, as it adheres to the RFC.

### Environment

Google Cloud Platform:
```
Google Load Balancer
```

Local Env:
```
OS macOS-10.15.7-x86_64-i386-64bit
Python 3.8.5
urllib3 1.26.2
```

### Steps to Reproduce

A simple and isolated way to reproduce the issue. A code snippet would be great.

### Expected Behavior

When a request is switched to GET, the body is dropped

### Actual Behavior

POST requests that receive a 303 status, are retried with a GET request containing the original body

**Comment by sethmlarson** [comment]
Unfortunately this HTTP status code is one where there's no "right" answer as I've heard the opposite being argued on the Requests issue tracker (Requests drops the HTTP body on the redirect). The safest way to go is if you're dealing with this HTTP redirect is to handle the redirect yourself by disabling redirects with `redirect=False` and changing the HTTP body to what you expect it to be.

**Comment by sigmavirus24** [comment]
I'd rather have a way of defining redirect policy that allows users to be specific so it could be disabled, etc.

**Comment by haikuginger** [comment]
I would be in favor of a default policy where, if the request method changes to `GET` from something else as part of a redirect, the body is dropped by default, to be augmented by the policy framework @sigmavirus24 suggests.

**Comment by ubdussamad** [comment]
So, is this feature going to be implemented @sethmlarson? Maybe `redirect` instead of just being a `boolean` can also be a simple class that could have a switch to purge the content incase of 303s?

**Comment by sethmlarson** [comment]
@ubdussamad Definitely would like to get this issue implemented. However it'd require the retry/ redirect flow to be able to communicate changes about the request which currently isn't implemented.

There's another issue on the v2 tracker about this, might be worth a look. 

If you wanted to start gathering requirements for this issue you should learn about our existing redirect and retry logic both in `PoolManager` and `ConnectionPool` and document it here so we can discuss what the minimum APIs we'd need.

**Comment by ubdussamad** [comment]
Hi @sethmlarson  , so I looked into the `urlopen` methods of both `PoolManager`& and `ConnectionPool`&.
In both (poolMgr and ConnPool) the redirect and retry objects are kind of disconnected.

The `redirect` variable is simply a boolean in both `urlopens`, which is passed to the retry
object's legacy constructor [`from_int`](https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py#L249) & on the first call to `urlopen` to create a proper [`retry`](https://github.com/urllib3/urllib3/blob/main/src/urllib3/poolmanager.py#L436) object **if
the request does not already has a `retry` object.**

The constructor [`from_int`](https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py#L249) usually set's a variable named [`total`](https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py#L205) to the default value which is [3](https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py#L506) and NOT [10](https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py#L188) **if `retries` is not a numeric entity.**

Now even if the variable `redirect` is `True` ( _and `retries` is left to default_ ) the `Retry` object will still raise an error if `total` number of retries (agnostic of the type of retry) which is 3 is reached. Because the `total` takes precendece over
all counts maybe it be redirect, read etc. So, unless we specifically provide a proper `Retry` object, we have limited
control because `form_int` always enables the `total` count which takes precendence over everything.

So for redirects, the `Retry` object is only responsible for raising an error if either we run out of `total` `retries` or 
we run out of permitted `redirects` ( _if a numeric `redirect` is provided with the `Retry` object_ ) **and** the
variable [`Retry.raise_on_redirect`](https://github.com/urllib3/urllib3/blob/main/src/urllib3/poolmanager.py#L455) is `True` (which is `True` by default). 

Thus, unless we specify number of `redirects` explicity, the `Retries` object dosen't really cares about `redirect` (True or False) and only carres about total retry count.

But in the methods `urlopen`, the `redirect` value (`True` or `False`) is used to decide wheather to either return
the `response` object or make another request to the changed host.
(Line [#425 ](https://github.com/urllib3/urllib3/blob/main/src/urllib3/poolmanager.py#L425) in poolmanager.py and [#803](https://github.com/urllib3/urllib3/blob/1831327b881880ed871f96f56a6977d360042e1b/src/urllib3/connectionpool.py#L803) in connectionpool.py)

For other errors, the logic is simimlar, if threshold is reached the retries object will raise an error else
make another request.

The only diffrence between poolManager's and connectionPool's `urlopen` is that the poolmanager supports
cross host redirects and connection pool's urlopen dosen't.

Now, in both `urlopen`s if a 303 does happen ([#433](https://github.com/urllib3/urllib3/blob/main/src/urllib3/poolmanager.py#L433) in poolmanager.py and [#805](https://github.com/urllib3/urllib3/blob/main/src/urllib3/connectionpool.py#L805) in connectionpool.py)
the `method` variable is changed to *GET* and it's here where we should modify things a bit.

First off, we should add a variable `remove_payload_on_redirect`:`bool` = `False` to the `Retry` class.
Which as mentioned is `False` by default, so old behavior isn't changed.
Now, when a 303 happens, we check if `Retry.remove_payload_on_redirect` is true or not and accordingly,
either set the body to `None` to let it be as it is.


My, understanding is that adding this change won't have any side effects and might not require much change.

**Comment by ubdussamad** [comment]
@SethMichaelLarson Is this what you wanted? Am I on the right track here?

**Comment by sethmlarson** [comment]
Completed in https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4
