### ISSUE TITLE
Allow passing pool kwargs via urlopen (for ssl like arguments)

### ISSUE THREAD

**Issue by IddoPuff** [urllib3/urllib3#2152]
### Context

What are you trying to do?
I am trying to use `poolmanager`s urlopen with `SSL_KEYWORDS`, which seems reasonable to me, as this is probably the most use function by external users.

How do you expect to do it?
in `PoolManager.urlopen` I would pass `kw` to the `connection_from_host` function.
then it will pass it forward until the `SSL_KEYWARDS` arguments in kw would trickle down
into functions that can use them
 
Is it something you currently cannot do?
I intend to open a PR to implement this in the immediate future

Is this related to an existing issue/problem?
I have reviewed the open issues and it seems to be new

### Alternatives

Can you achieve the same result doing it in an alternative way?
Is the alternative considerable?
This doe's not seem relevant to this issue.
Unless you mean use another library which seems irrelevant

### Duplicate
not that I've seen

### Contribution

Would you be willing to submit a PR?
Yes, I will submit a PR, and would love to get reviewed

**Comment by pquentin** [comment]
Thanks for opening this. Pardon my ignorance, but what are `SSL_KEYWORDS`? Can you provide a code snippet explaining how you would use this new feature?

**Comment by bluetech** [comment]
I don't know what `SSL_KEYWORDS` is, but here is my use case:

I have a `PoolManager` which handles connections to several hosts. One of these hosts uses SSL client certs, so I need to pass the `cert_file` and `key_file` arguments. However, `urlopen` doesn't accept these arguments. So instead of this:

```py
poolmanager.urlopen(method, url, cert_file='...', key_file='...')
```

I need to write this:

```py
conn = self.http_client.connection_from_url(url, pool_kwargs=dict(cert_file='...',  key_file='...',))
response = conn.urlopen(method, url)
```

This would have been fine, though slightly obscure, but the problem with this is that it bypasses all of the logic in `PoolManager.urlopen`, besides making it impossible to use the higher-level helpers like `PoolManager.request`.

It would seem a very simple way to resolve this would be to add a `pool_kwargs` argument to `PoolManager.urlopen`, that is, you'd write this:

```py
response = conn.urlopen(method, url, pool_kwargs=dict(cert_file='...',  key_file='...',))
```

and `urlopen` would pass it through to the internal `self.connection_from_host` call. But I haven't thought it through yet.

**Comment by sethmlarson** [comment]
For now we have no plans to support per-request differences to TLS options. This likely won't change without a new API entirely (PoolManagerManager?) Going to close this one.
