### ISSUE TITLE
[v2] Use httplib's chunked encoding support?

### ISSUE THREAD

**Issue by bluetech** [urllib3/urllib3#2291]
`urllib3.HTTPConnection` has a method [`request_chunked`](https://github.com/urllib3/urllib3/blob/89ca490bfc15b7b4762676b5b51bf57e8912d80f/src/urllib3/connection.py#L287) which sends the body with chunked encoding. [Since Python 3.6](https://github.com/python/cpython/commit/3c0d0baf2badfad7deb346d1043f7d83bb92691f), httplib supports this directly, with very similar-looking code. Since v2 now requires Python 3.6, I was wondering if we might want to use this.

I haven't checked if there are any gotchas there, this is more of a placeholder issue since I couldn't find an existing issue discussing this.

**Comment by sethmlarson** [comment]
Kind-of related to this, I was wondering if we should instead add a `chunked` parameter to `HTTPConnection.request()` and shim `.request_chunked()` to simply call `return self.request(..., chunked=True)`. Reasoning being that the rest of our API looks like this, seems more natural to have `.request(..., chunked=True)` everywhere instead of at every level until you get to `HTTPConnection` and suddenly a shift to two different methods?

**Comment by sethmlarson** [comment]
The above change would also bring us closer to the stdlib's implementation but keep things urllib3-flavored, we're already married to the `chunked` parameter (and I like it better than `encode_chunked` tbh)
