### ISSUE TITLE
Handle `https:///`, `https:/` and `https:\` as `https://`

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#2368]
### Subject

parse_url in urllib3 mishandles certain uses of extra slash or backslash (such as `https:///`, `https:/`, `https:\`) and interprets the URI as a relative path. Browsers accept extra slash or backslash after the protocol, and treat it as a normal slash, while parse_url sees it as a relative path.

Full disclosure: this was originally sent to us as a security vulnerability, but as the report shows, with those URLs we don't detect any hosts. That means that any request with those URLs will fail with "urllib3.exceptions.LocationValueError: No host specified.". So no SSRF is possible.

### Steps to Reproduce

```
import urllib3
url1=urllib3.util.parse_url('https:///www.attacker.com/a/b')
print("HOSTNAME:  " +str(url1.host))
print("PATH    :  " +str(url1.path))
url2=urllib3.util.parse_url('https:/www.attacker.com/a/b')
print("HOSTNAME:  " +str(url2.host))
print("PATH    :  " +str(url2.path))
url3=urllib3.util.parse_url('https:\www.attacker.com/a/b')
print("HOSTNAME:  " +str(url3.host))
print("PATH    :  " +str(url3.path))
```

### Expected Behavior

Do what browsers do: all those URLs should be treated as `https://www.attacker.com/a/b`.

### Actual Behavior

```
HOSTNAME:  None
PATH    :  /www.attacker.com/a/b
HOSTNAME:  None
PATH    :  /www.attacker.com/a/b
HOSTNAME:  None
PATH    :  /%5Cwww.attacker.com/a/b
```

**Comment by chetanugale** [comment]
@pquentin can I pick this issue?

**Comment by pquentin** [comment]
Sure!

**Comment by timmc** [comment]
While some browsers do "fix up" URLs in that way, that is contrary to [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986), which makes no such allowance. Adding such variations increases the chance of a parser mismatch vulnerability as seen in Claroty's excellent [paper on URL parser confusion](https://claroty.com/wp-content/uploads/2022/01/Exploiting-URL-Parsing-Confusion.pdf).

The WHATWG guidance on URLs does suggest treating backslashes as slashes, but it is driven by observed usage in browsers, and is subject to change. As such, it is not a stable standard that can be targeted for correctness and compliance.

I would strongly recommend hewing to RFC 3986 as closely as possible in order to reduce the number of vulnerabilities that will stem from mismatches between the behavior of this parser and others. That includes not trying to fix up malformed scheme separators.

**Comment by sethmlarson** [comment]
Yeah, this issue+PR being around for so long are mostly due to me not wanting to merge this change. This came in as a security issue iirc, but I'm not even sure it's a "bug" that we're strictly following RFC 3986. I think we're going to decline this change unless stronger evidence comes around in the future.
