### ISSUE TITLE
Try our test suite against PyPy 7.3.6 (Python 3.8 beta)

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#2486]
We currently test against pypy-3.7 but last month PyPy 7.3.6 added beta support for Python 3.8. @pquentin psubmitted an issue](https://foss.heptapod.net/pypy/pypy/-/issues/3539) that was fixed and released in this beta version, we should test the beta version before a stable release to see if the fix was successful.

We don't necessarily need to run this test suite on every PR yet (although that is welcomed, not sure how feasible it is though?)

**Comment by hugovk** [comment]
PyPy 7.3.7 is also out now:

* https://www.pypy.org/posts/2021/10/pypy-v737-release.html

(There's no mention of beta in the 7.3.7 release, and [7.3.6](https://www.pypy.org/posts/2021/10/pypy-v736-release.html) said 'Since this is our first release of the interpreter, we relate to this as "beta" quality' so maybe 7.3.7 isn't beta?)
