### ISSUE TITLE
Automatic links from code examples to reference documentation

### ISSUE THREAD

**Issue by felix-hilden** [urllib3/urllib3#2491]
### Proposal
Hi! I'd like to propose an improvement to urllib3's documentation. The change would make urllib3's functions and classes in code examples clickable to take the user to their reference documentation entries. I've built the documentation locally for a proof of concept, so here's the home page example:

![home page links](https://user-images.githubusercontent.com/25202257/142902973-70baccf9-069f-4fb9-a61e-8d55d3d048cd.png)

It would use the [`sphinx-codeautolink`](https://sphinx-codeautolink.rtfd.io) extension to automatically analyse the examples and produce links.

### Context
Full disclosure: I'm the author of said extension. I spent the weekend building a bunch of different Python projects with it and fixed lots of issues. urllib3's case was very neat though, so I decided to propose this to you directly. The library is in beta, but based on local testing it worked well. Currently the setup is only two lines of code in `conf.py`: activating the extension and configuring an "import urllib3" to be included before all examples:

```python
extensions = [
    ...,
    "sphinx_codeautolink",
]
codeautolink_global_preface = "import urllib3"
```

### Alternatives / against the change
The current solution of linking the relevant function before every example certainly works quite well especially since the examples are pretty simple, containing very few different functions per snippet! Perhaps some links could be stripped out if this change is adopted though. Also, it could be not entirely obvious that the code examples are clickable, leading to some confusion.

### Contribution
I'd be willing to submit a PR for sure, once we figure out the details!

---

What do you think, would it be a good fit? If you don't like the change, feel free to shoot me down immediately! I recognise this could be just adding some maintenance burden for little gain, but personally I think the links make user experience much better. Also, let me know if you have any questions!

**Comment by sigmavirus24** [comment]
How does this help when the rest of the code base is typically documenting things referenced on the exact same page, if not immediately before? Does this not create yet more confusion as the user hovers over it and wonders "Where does this take me?" when it just takes them a few paragraphs up?

**Comment by felix-hilden** [comment]
Do you mean the examples in reference documentation? Sure, that could be another case of slight indirection. I think most of the value would be in "User guide" and "Advanced usage".

**Comment by sigmavirus24** [comment]
> I think most of the value would be in "User guide" and "Advanced usage".

So your image is from the home page which is meant to illustrate super basic usage. It's front-page advertising. It's like showing how a child might play with a toy that requires assembly on the outside of a box. I don't think that code sample needs this treatment because it bypasses where we _want_ users to go (the User Guide to start with) who are new to urllib3 and passes them directly into the less helpful reference documentation.

> I think most of the value would be in "User guide" and "Advanced usage".

These are narrative style documents. They link both to the reference documentation directly and to additional narrative documentation as necessary. Given the proximity of the existing reference documentation links, I don't know how much adding this would help given every code-block is short and either prefixed or suffixed (or in a couple cases I noticed while scanning, both) by links to reference and other narrative documentation. I don't think we'd want to remove those links in favor of generated  links from your plugin, because the code being clickable is not an immediate affordance people will be used to.

Making the code links also seems to interfere on your plugin's own documentation site, with being able to copy things easily. Instead I now need to make sure I don't accidentally click a link that isn't otherwise visually hinted at being a link because I can't know which code block might have this enabled and which doesn't.

I think this is a _very clever_ plugin for spinx. I don't think that makes it necessarily right for all use-cases.

**Comment by felix-hilden** [comment]
Entirely fair! As I said, the simple examples and relatively short documents could mean that urllib3's case is hurt more than aided by removing the prose links.

> Making the code links also seems to interfere ... with being able to copy things easily.

Noted, I appreciate the feedback 👍

**Comment by sethmlarson** [comment]
First off, this plugin is really awesome. Excellent work on it! :clap:

As much as I love magical plugins, I'm leaning towards what @sigmavirus24 said in that we want users to end up in "User Guide" instead of "API reference". However the links themselves are fairly unassuming and don't pull your eyes into them. If you had time I'd love to see a PR adding the plugin if only to see it in action with Furo. Would you be up for that?

**Comment by felix-hilden** [comment]
I think the ping missed me, but anyways, thank you for the kind words!

With his well-thought-out explanation, I think I agree too. But I'd love to help if I can! Your theme is Furo already, so what do you mean? Or simply submitting a PR to see it in action fully?

**Comment by sethmlarson** [comment]
@felix-hilden Yeah! We build our docs on every PR and they can be viewed in a staging environment on RTD.

**Comment by felix-hilden** [comment]
I'm sure you got the notification anyway, but the PR is now live!
