### ISSUE TITLE
py.typed removed from dist package data

### ISSUE THREAD

**Issue by symonk** [urllib3/urllib3#2729]
Hi there, minor one I notice when moving to `flit` via [this commit](https://github.com/urllib3/urllib3/commit/8ab5eb83a0bf359f5372a8eff2b07f46fe34203d) the `py.typed` file was no longer exported which causes mypy to complain about urllib3 (`types-urllib3` is an option via `typeshed`)  Was that an intentional change, is it preferred to use that via typeshed?

```
error: Skipping analyzing "urllib3": module is installed, but missing library stubs or py.typed marker
```
I see some comments [here](https://github.com/urllib3/urllib3/pull/2296) which references this not being the case or guarding it from happening.

Thanks a bunch, happy to fix it if it was not intentional

**Comment by sethmlarson** [comment]
There might be a misunderstanding here due to how we do branching. Our only released branch is 1.26.x, the main branch hasn't been released yet. We also haven't released any py.typed file from 1.26.x yet.

You might have to install `types-urllib3` from now on since typeshed isn't included by default with mypy anymore? I recall there also being an `--all-types` option too?

Going to close this as it's not an issue, let me know if there's further questions.

**Comment by pquentin** [comment]
I double checked and if you build a wheel from the main branch with `python -m build` the `py.typed` file is correctly included.

**Comment by symonk** [comment]
@sethmlarson @pquentin thank you both, I was just checking versions distributed here: https://pypi.org/project/urllib3/#files
