### ISSUE TITLE
Websites with multiple "." in domain name raise ssl_match_hostname.CertificateError

### ISSUE THREAD

**Issue by kaushik98y** [urllib3/urllib3#2738]
### Subject

As above mentioned.

### Environment
python 3.7
urllib3 1.26.9

### Steps to Reproduce

Was crawling using scrapy, got ssl_match_hostname.CertificateError
### Error: 
Traceback (most recent call last):
  File "../venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "../venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "../venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.lovingtx.countygovernmentrecords.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'www.lovingtx.countygovernmentrecords.com' doesn't match either of '*.countygovernmentrecords.com', 'countygovernmentrecords.com'")))

### Response with multiple "." causes the above error 
example as fetched in above log stack www.lovingtx.countygovernmentrecords.com

**Comment by pquentin** [comment]
Hello! And thank you for taking the time to report your issue. Unfortunately, this bug report is invalid. The error is not that urllib3 does not support multiple dots, it's that the certificate for https://www.lovingtx.countygovernmentrecords.com/ is invalid. Try this link in your favorite browser, you will see the same error.

https://lovingtx.countygovernmentrecords.com/ works because the certificate is valid for `*.countygovernmentrecords.com`.
