### ISSUE TITLE
Import ".packages.six.moves.http_client" could not be resolved

### ISSUE THREAD

**Issue by AlexanderBodnar1** [urllib3/urllib3#2812]
### Subject

The import .packages.six.moves.http_client not found.

![image](https://user-images.githubusercontent.com/116795167/202105854-c34a457c-0701-45f9-bbc9-4014d8c44d96.png)
![image](https://user-images.githubusercontent.com/116795167/202106110-fe2712a8-ef39-4f04-9e26-f94777b91f91.png)

What is the problem here?

### Environment

I have already installed the newest version of urllib3 and i additionally installed the six module aswell but it didn't help. I'm running python on a virtualenv.

![image](https://user-images.githubusercontent.com/116795167/202106607-afadbcf4-2f89-4205-b1a9-dd2684a933fb.png)

### Expected Behavior

It should establish connection with the sharepoint server.

### Actual Behavior

What happens instead.
It crashes because of the imports missing in the connection.py file

**Comment by pquentin** [comment]
The squiggly lines in your editor are not an issue. `.package.six.moves` is dynamically created, which is why you editor cannot see it.

The issue is that getaddrinfo failed. That means that the host you were trying to use did not resolve to an IP address. This does not appear to be an urllib3 issue. I would suggest trying Stack Overflow instead, giving more details about your sharepoint server.

**Comment by Ancolie18** [comment]
have u solve this issue?  I meet the same problem

**Comment by AlexanderBodnar1** [comment]
Hi, Yes I have fixed the issue. As the comment above says this is normal. The package is dynamically created so that’s why the editor cannot see it. However I had an issue with the connection itself. I managed to fix the issue by running a proxy when connecting to the sharepoint. In my case this fixed the issue 😊.
