### ISSUE TITLE
Assess impact of cpython/gh-96931 (shared_ciphers)

### ISSUE THREAD

**Issue by Ousret** [urllib3/urllib3#2955]
### Subject

It most likely has a minor impact, but worth reporting.
I suspect we will shortly see the test suite failing consistently soon.
`SSLSocket.shared_ciphers()` can return None, starting next interpreter minors in `>=3.10`.

### Materials

Original issue: https://github.com/python/cpython/issues/96931
Patch: https://patch-diff.githubusercontent.com/raw/python/cpython/pull/96932.patch
PR: https://github.com/python/cpython/pull/96932

Judging by the patch, the current behavior is deemed incorrect. 

### Test to watch

```
FAILED test/test_ssltransport.py::SingleTLSLayerTestCase::test_ssl_object_attributes - AssertionError: assert <class 'NoneType'> == list
```

**Comment by yan12125** [comment]
> Judging by the patch, the current behavior is deemed incorrect.

Yep that seems the case. The tested socket in `test_ssl_object_attributes` is a client socket, and `SSLSocket.shared_ciphers()` returns `None` for client sockets per [1]. The document hasn't been changed since long time ago, and Python 3.11.3 and 3.10.11 fixes the code to match the document.

[1] https://docs.python.org/3.10/library/ssl.html#ssl.SSLSocket.shared_ciphers
