### ISSUE TITLE
Consider HTML 5 draft for multipart/form-data

### ISSUE THREAD

**Issue by gagern** [urllib3/urllib3#303]
In several past posts, I've tried to make urllib3 more standards-compliant, the way I saw things. In particular, #120 aimed at adding a proper `Content-Type` header for _every_ form field, and #119 / #223 introduced [RFC 2231](http://tools.ietf.org/html/rfc2231) format for file name encoding.

One consequence of that last change was my noticing that tornado doesn't decode that format, causing some test cases to fail. e11e03628f8b82021a74ba7f5b39ce9ad9011382 monkey-patched tornado to deal with that, and I filed facebook/tornado#868 to take this upstream. There [bdarnell pointed out](https://github.com/facebook/tornado/pull/869#issuecomment-23632083) the following:

**The current HTML 5 draft has [a section on multipart/form-data](http://www.w3.org/html/wg/drafts/html/master/forms.html#multipart-form-data) which explicitely forbids the use of `Content-Type` for non-file fields, and also the use of RFC 2231 format for file names. It also provides its own mechanism for encoding field names.**

Although I'm reluctant to abandon conformance with Standards Track RFCs for the sake of some lines in a draft, it appears that the HTML 5 draft might better reflect what current web servers actually implement, or are going to implement in the intermediate future. Perople have already [reported problems](http://stackoverflow.com/q/20591599/1468366) with our format in the wild. For this reason, I wonder whether the current choice of always using RFC 2231 might have to be revised.

I can imagine two approaches, one would be dropping RFC 2231 support completely, the other would be introducing some switch to distinguish cases. I guess (although I don't like it) that the switch should default to the HTML 5 way. I guess I'd implement the switch as a global variable, since every field needs acces to it and concurrent use of multiple standards should be very unlikely. Do you have a better suggestion?

So what would be needed for HTML 5 conforming handling of encodings? We'd need to properly distinguish between files and non-files. The [`RequestField` class](https://github.com/shazow/urllib3/blob/master/urllib3/fields.py#L53) could probably check whether both file name and content type are `None` to recognize non-file fields. That choice could be used to control the addition of the `Content-Type` header.

For file names, we'd have to encode them to UTF-8 (or some user-configurable request encoding?), after making sure the result does not contain any invalid data: newlines must be stripped (or converted to spaces), quotation marks and backslashes quoted by `\` or substituted. I'm not sure which of these, and how much control we want to give our users over that process.

If we allow for encodings other than UTF-8, which are not able to represent all Unicode codepoints, then we might need some more work. File name characters which are not representable must then be substituted or approximated somehow. For filed names we'd have to make sure we replace non-representable characters as XML decimal character entities instead. Other non-ASCII header fields should usually not occur, but if they do, I guess they should be treated the same way file names are.

I notice that I made a mistake in reading [RFC 2388](http://tools.ietf.org/html/rfc2388): its [section 5.4](http://tools.ietf.org/html/rfc2388#section-5.4) states that field names are subject to a different encoding than file names. Grrr! Whoever though of that?!? In any case, to be conforming to that as well, we might even want to revise the RFC2231-using mode if we decide to keep it at all.

I might find the time to write some of this myself, but before I start, I'd like to discuss the open questions above as to how this should get implemented.
##

**Comment by Spryttan** [comment]
The above summary and links were very helpful in understading the situation, thanks! Unfortunately, there still isn't a single, clear, widely adopted way to encode non-ascii file names, and web servers don't agree on what format they accept. It's a fairly simple monkeypatch to workaround if you're interacting with a single web server, but there is still a need to be able to change encoding formats per-request. @shazow @gagern Is any one working on this (or even wants to)? 

Also, here is an unbroken link to the relevant section in the current HTML5 draft: [multipart-form-data](http://w3c.github.io/html/sec-forms.html#multipart-form-data)

**Comment by shazow** [comment]
I'm not aware of anyone working on it, so you're welcome to claim it. :)

**Comment by Spryttan** [comment]
I just submitted a pull request, #856, which is a proposed solution (with some code from #304) for just one aspect of this issue: encoding non-ASCII file names the HTML5 way by default. I organized this so that the concept of a file name encoding style was kept within the `RequestField` class, which means that it can only be chosen at the time of construction of a `RequestField` (i.e. `__init__` or `fromtuples`). 

These are the things which aren't included:
- Encoding a non-ASCII field name parameter
  
  [This StackOverflow answer](http://stackoverflow.com/questions/20591599/why-arent-post-names-with-unicode-sent-correctly-when-using-multipart-form-data) has good collected information on this, but there's no clear answer in theory or practice, so I don't think I'm going to work on this. But if it was decided RFC 2047 is a good choice, `email.header.Header.encode` will encode it.
- Allowing for form-data encodings other than utf-8
  
  I'm not going to submit code for this either (in this PR), but I thought the latest version of #304 had a good solution: controlling this by a keyword parameter of `filepost.encode_multipart_formdata` and moving the codecs lookup to within the function.
- Only setting the Content-Type header for non-file fields

  I think this is different enough from the other points to be fixed in a separate PR.This will make it easier to code and review too.

**Comment by zigarrre** [comment]
Will this ever be fixed?

Over 4 years have passed and HTML 5 isn't a draft anymore but an official standard.

All major browsers now do it this way and most servers cannot handle the `filename*` field with RFC2231 encoding.

But urllib3 is still using the RFC2231 encoding which not only doesn't work in the real world but is also a clear violation of current standards.

**Comment by haikuginger** [comment]
@sigmavirus24, would like your thoughts on this.

**Comment by sigmavirus24** [comment]
Some thoughts on this:

1. RFC2231 does work in the real world, but in spite of being a standard, it's not implemented in every http server
1. We have built into this library a whole separate library for dealing with multipart/form-data, instead any future improvements should be developed as an external library (in my opinion) and (maybe) vendored in.
1. Unfortunately, a quick search of pypi indicates no one has implemented this yet
1. Provided the fact that for probably 90% of our users the status quo just works, I'm not sure how urgent this issue is, regardless of its age

**Comment by zigarrre** [comment]
> 1. RFC2231 does work in the real world, but in spite of being a standard, it's not implemented in every http server

RFC2231 is the completely wrong standard here and does not apply. The HTML5 spec has a description of how to properly encode multipart/form-data: https://www.w3.org/TR/html52/sec-forms.html#multipart-form-data

RFC7578 (which is referenced by the HTML5 spec) also very clearly states that the current way urllib3 does it (using the `filename*` field) is wrong:

> NOTE: The encoding method described in [RFC5987], which would add a
   "filename*" parameter to the Content-Disposition header field, MUST
   NOT be used.

Many - if not most - server implementations in the real world will NOT work with the current way urllib3 does it (e.g. any PHP applications).

> 4. Provided the fact that for probably 90% of our users the status quo just works, I'm not sure how urgent this issue is, regardless of its age

As this is only a problem if one tries to send non-ASCII characters in a non-file field of a multipart encoded form many of your users wont notice this problem in the first place and the rest has resigned to using a workaround or a different library. But still you will find a huge number of people discussing this problem of urllib3 with just a quick search. So this is not a valid argument.

As I understand the standards this should be a rather easy fix as well. Just using `filename` instead of `filename*` and UTF-8 instead of RFC2231 should be enough in most cases.

**Comment by sigmavirus24** [comment]
> Just using filename instead of filename* and UTF-8 instead of RFC2231 should be enough in most cases.

This is not actually our experience, otherwise we wouldn't have gone through the trouble to implement RFC2231. 

@zigarrre you seem passionate about this and seem to have time on your hands. We'd be open to using a library that you would produce that would do the correct thing per the HTML5 spec.
