### ISSUE TITLE
No way to perform request for raw urls

### ISSUE THREAD

**Issue by SaturnIC** [urllib3/urllib3#3062]
## Overview
There is no way in the current state of urllib3 to perform a request for raw urls,
because encoding is always done implicitly.

## Description
- `urllib3/connectionpool.py HTTPConnectionPool::urlopen(...)`
- Calls `parsed_url = parse_url(url)`, which transforms urls to RFC 3986 compatible urls implicity.
- For testing purposes it is necessary to send deliberately malformed urls, but there is no way to do that with urllib3 because there is no option to provide raw urls.

## Proposal
- Please provide a way to set raw urls that will not be transformed implicitly

**Comment by pquentin** [comment]
We document that connection pools are a way to avoid parsing URLs, see https://urllib3.readthedocs.io/en/stable/reference/urllib3.connectionpool.html#urllib3.connectionpool.ConnectionPool. And there's even a test, see the discussion in https://github.com/urllib3/urllib3/issues/1790 for details.

Maybe we missed something at the time or we regressed since then?

**Comment by pquentin** [comment]
I looked a bit closer. We don't rely on the output `parse_url` in `HTTPConnectionPool.urlopen()` as long as the URL correctly starts with `/`. And in all cases we percent-encode invalid characters, indeed. So you can query `/../../foo/bar` but not an URL without a starting slash or invalid characters.

 I don't think urllib3 is the right tool to use if you want to query malformed URLs. What you call a necessity could also be considered a vulnerability. Have you tried using https://docs.python.org/3/library/http.client.html instead?
