### ISSUE TITLE
EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by rsuffert** [urllib3/urllib3#3120]
First of all, I'd like to say that I have seen several people report this error, but most of them could not fix it and, those who could, did not share how they did it. Hence I am adding this issue, hoping that we can find a definitive solution for this problem and that other people who come across the same issue can use this as reference.

### Subject

I am attempting to upload a `.tar.xz` file (whose content is represented in the code below by the `update_pkg_content` variable) to a remote server with the following headers and body:
`        headers = {
            "Content-Type": "multipart/form-data"
        }`

`        body = {
            "UpdateParameters": (None, json.dumps({'Targets': targets, 'Oem': {}}), 'application/json'),
            "UpdateFile": (update_pkg_path.split("/")[-1], update_pkg_content, 'application/x-xz')
        }`
It is a Redfish server, so I'm using Python's `redfish` library to send the request: `self.REDFISH_OBJ.post("/redfish/v1/UpdateService/MultipartUpdate", headers=headers, body=body)`. That Redfish object is working properly for the other dozens of endpoints of the server, but, for this specific one, where I'm submitting an update package, I get a `urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:2426)`, which leads to a sequence of at least three other errors caused by that excpetion raised by `urllib3`.

Maybe it is worth mentioning that this is a large request: `"Content-Length": "436063339"`.

### Environment

`OS Linux-6.2.0-26-generic-x86_64-with-glibc2.35
Python 3.10.12
OpenSSL 3.0.2 15 Mar 2022
urllib3 1.25.11`

### Steps to Reproduce

Send a request similar to the one describe above.

### Expected Behavior

The server should receive the request, accept it, and begin the update process.

### Actual Behavior

An exception stating that "EOF occurred in violation of protocol" is being raised by `urllib3`.

**Comment by sigmavirus24** [comment]
> Hence I am adding this issue, hoping that we can find a definitive solution for this problem and that other people who come across the same issue can use this as reference.

This is unrealistic as a goal. This problem has many potential causes. Fundamentally what is happening is that the server you're speaking to (or an intermediary) is closing the socket after the handshake completes in violation of the state machine that is relevant to the socket and TLS connection.

I can potentially guess as to the problem you're having, but I know nothing about redfish as a service or redfin as a client library for it. Also, there's no way to know what infrastructure might be between your client and your server, so it truly is up to you to determine what your problem is in particular here, rather than for us to magic our way to a solution why any number of causes.

**Comment by sethmlarson** [comment]
Closing this as we won't be able to reproduce this issue and it's not clear this is a defect in urllib3.
