### ISSUE TITLE
fix for AIX ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by pdunbarp** [urllib3/urllib3#3133]
Hi 

I have this issue with AIX 7.3 but don't see it listed in the OS affected

ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2u 20 Dec 2019'. See: https://github.com/urllib3/urllib3/issues/2168

is there a fix available for AIX 7.3?

Thank You

**Comment by pquentin** [comment]
Hello,

As mentioned on Discord, this issue is not specific to AIX in any way. To use urllib3 v2.0, you need OpenSSL 1.1.1+ as older versions of OpenSSL are no longer supported by the OpenSSL project and are likely to contain security issues, unless specifically patched. (OpenSSL 1.1.1 support was dropped by the OpenSSL project this month, so it's even better to switch to OpenSSL 3 if possible).
