### ISSUE TITLE
Cannot close connection

### ISSUE THREAD

**Issue by snooppr** [urllib3/urllib3#3189]
```
$ python

import urllib3

resp = urllib3.request("GET", "https://fantlab.ru")
resp.close() #I expect the connection to get the TIME_WAIT status, but the connection continues to have the ESTABLISHED status.
```
The connection closes completely when I exit the console.

OS Debian 10
python3.8.7
OpenSSL 1.1.1k  25 Mar 2021
urllib3 2.1.0

I described the “error” in more [detail](https://github.com/psf/requests/issues/6573) when I encountered the use of the requests library.

**Comment by sethmlarson** [comment]
That is because we do connection pooling in the background so that subsequent requests can take advantage of an already-open socket. There is a limit on the number of concurrent connections that can be open at one time. Calling `resp.close()` only drains the remaining unread HTTP response body if any and then marks the connection as available to use within the pool.
