### ISSUE TITLE
[SECURITY] Clarify/Simplify HTTPSConnection.connect 

### ISSUE THREAD

**Issue by abebeos** [urllib3/urllib3#3287]
### Context

In order to avoid security related bugs in future, the method `HTTPSConnection.connect` should be revised.

This came up during #3267/#3283

### Process

- [x] provide property `proxy_is_forwarding` 
  - done within https://github.com/urllib3/urllib3/pull/3283)
- [ ] https://github.com/urllib3/urllib3/issues/3285
- [ ] Further strict refactoring (zero functional change)
  - focus: Clarity, simplicity

Ideally execute this in parallel with related issues

- #2791
- #2577
- ... ?

**Comment by sethmlarson** [comment]
I would prefer not to refactor things without a clear reason to, what needs to be refactored? And I am confused why you are linking to many issues with a checklist which stand on their own in this issue?

**Comment by abebeos** [comment]
> I would prefer not to refactor things without a clear reason to,

Reason: RCFA of several bugs leads clearly to "lack of code clarity/simplicity". (the super-root-cause is most possibly "lack of available time")

> I am confused why you are linking to many issues with a checklist

The issues are related to `https`. It is more efficient (and sometimes necessary) to clarify/simplify code in parallel.

Maybe just try this out with a tiny budget to get clarification from the results?

**Comment by abebeos** [comment]
> issues with a checklist

Removed the 2 redundant checkboxes

**Comment by sigmavirus24** [comment]
> > I would prefer not to refactor things without a clear reason to,
> 
> Reason: RCFA of several bugs leads clearly to "lack of code clarity/simplicity". (the super-root-cause is most possibly "lack of available time")
> 
> > I am confused why you are linking to many issues with a checklist
> 
> The issues are related to `https`. It is more efficient (and sometimes necessary) to clarify/simplify code in parallel.
> 
> Maybe just try this out with a tiny budget to get clarification from the results?

@sethmlarson has already explained how bounties are decided and assigned. There's no agreement from maintainers that connect needs refactoring and using acronyms that aren't well known doesn't help make your point. (I don't know what the red carpet fashion awards have to do with anything here. 😜)

There's no agreement here. If you want to prove it's necessary feel free but refactoring that will only likely further frustrate you because those reviews will take a great deal of time to ensure nothing breaks or regresses. If there were a bounty you would only be more angry and hostile towards the maintainers because you wouldn't get paid as quickly as you seem to insist you should be (on pull requests still under review).

**Comment by abebeos** [comment]
@sigmavirus24 , maybe go find some junior-devs to patronize and emojize?

As usual, I am awaiting a decision from the decision taker(s), after replying with some arguments and a correction.

(And its not my loss if the decision is negative, but the projects/users/sponsors. I've for now enough work that interests me here.)

**Comment by sigmavirus24** [comment]
@abebeos To be clear, you claim to have lots of experience in technology but none of your behaviours exhibit that to me. So forgive me if it seems I'm patronizing you.

Let me give some examples:

1. Someone with as much experience as you claim to have would have worked in enough contexts to know that if the "decision taker(s)" ask for a change in behaviour, the response is to take a step back and evaluate what needs to change - Do you need to change? Do the other people need to change? What needs to change? Are those changes aligned with my priorities? If they're not, how do we move forward?
2. Someone with as much experience as you claim to have would prioritize clear communication above all else, not communicating what seem to be nascent ideas in what seems to be a note-taking format understandable primarily to you. This requires significantly more energy from "decision taker(s)" to align with what you see as the problem and potential solutions. That means people are less likely to want to look at or respond to your issues, PRs, etc. 
3. Someone with as much experience as you claim to have would understand that no two project teams work exactly the same. Whatever standards supposedly exist, there are N other standards that exist to unify the prior N-1 standards. No matter what standard you prefer, there will be people with other priorities, other ways of working, and other ways of executing that may be better, worse, or the same as yours. Asserting your own personal standards as the one way, is not an effective use of anyone's time. And people are allowed to say "no", or "some of these make sense, but I'm skipping the rest" even if that is communicated through "We did x and now I'm closing this" without having to respond to a "Don't close this you didn't do exactly what I said [my paraphrasing and expanding what how you said came across]".
4. Someone with your experience might look at who has spent the most time giving you constructive feedback on your changes and at the project they're contributing to and determine who is a decision taker. (I'm not offended, I just continue to be entertained that you seem to think I'm not a decision maker here.)
5. Someone with your experience might endeavor to learn more about how to collaborate on a new project, rather than asserting that everything in the project is too slow or broken because your priorities and the project's priorities/availability aren't aligned. Instead of going to other projects and complaining, you can have many options:
  a. Stop contributing as much as you because your priority is to get paid, and this project's priority is to deliver certain items with rock solid stability.
  b. Realign how you contribute so that if you feel a bounty is insufficient, you don't do that work. No one is making you do it. It will get done. Heck, if it's sat long enough and is a high enough priority, we'll probably increase the bounty eventually to something that is more than worth your time and effort on it.
  c. Stop contributing altogether. You seem very unhappy working on this project. Your only motivation is the bounties. You've made it clear the bounties aren't enough and aren't paid fast enough. As a result, maybe wrap up the PRs you have and move on to another project that works the way you want it to. We didn't ask you to come and insist on bounties for things, or complain here and elsewhere about how low the bounties are, or to open issues that take a lot of energy and time to understand and collaborate with you on.

The priorities of this project are pretty clear:
* Security is #1 always and foremost that means things that are security sensitive get a lot of attention and potentially less refactoring to keep things safe and stable
* Make an excellent, rock solid library that does the right things
* Foster an environment of collaboration with excellent communication and by rewarding work on things that are a high priority to deliver
* Have fun with what we're doing (some of us are unpaid volunteers and are doing this for fun)

And maybe Seth, Quentin, and others have other priorities in addition to this, but I don't think the above four are wrong.

**Comment by abebeos** [comment]
> @abebeos To be clear, you claim to have lots of experience in technology but none of your behaviours exhibit that to me. So forgive me if it seems I'm patronizing you.
> 
> Let me give some examples:
[...]
I won't go into this, i am not even reading this (besides sampling to get the tenor), as It's already difficult to focus due to the nature or this project. 

I suggested a (necessary) task, based on this:

>If you have a proposal to work on urllib3 that’s not listed in the issue tracker please open an issue with your proposal and our team will discuss whether we’d pay for your work on your proposal.
https://urllib3.readthedocs.io/en/stable/contributing.html

Decision takers can now either agree or not.

It's that simple.

**Comment by abebeos** [comment]
@sigmavirus24 , I moved your comment over to my fork (https://github.com/abebeos/urllib3/issues/5). I maybe go through it when I am off-code, or in combination with processing https://github.com/abebeos/urllib3/issues/3.

**Comment by sigmavirus24** [comment]
> I won't go into this, i am not even reading this

I am trying to give you feedback that will improve your experience with the project and the project's experience with you. It seems your approach is to ignore feedback and ignore people rejecting your ideas instead.

Put another way, what's currently happening is that most maintainers are not fond of working on the issues or pull requests you're creating because you don't behave collaboratively. If you continue in your current behaviour you will only grow angrier at the lack of engagement and slow bounty process (as you have made it clear that you're only here to make the pittance - in your opinion - that's paid for a bounty). That's likely going to result in a violation of the code of conduct which will require action.

---

As for this issue, as a decision taker agreeing with @sethmlarson and as someone who asked how things are insecure today without an answer, **I'm rejecting this issue**
