### ISSUE TITLE
Add http_version property to BaseHTTPResponse

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#3297]
Now that HTTP/2 is coming we should add a value to HTTPResponse to provide this value. The normal HTTPResponse will either be HTTP/1.1 or HTTP/1.0. Check `_http_vsn_str` for that value.

**Comment by pquentin** [comment]
Turns out `BaseHTTPResponse` already has a `version` field, which gets populated from `http.client.HTTPVersion.version`. It's an integer mapped from the [HTTP-version field](https://www.rfc-editor.org/rfc/rfc9112.html#name-http-version) in the start line. For example, `HTTP/1.1` is mapped to 11: https://github.com/python/cpython/blob/b822b85ac11e73bbe4417bf03ee770ab116bb42d/Lib/http/client.py#L342-L348.

While arguably more ugly than using the full string or even the [ALPN name](https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids), according to [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-protocol-version) it's OK to assume that a protocol will be two digits (major and minor), with the second digit being 0 if not specified.

Two decisions are needed here:

 1. Do we add a new `http_version` field and fill it with `HTTP/1.1` or `HTTP/2`?
 2. Do we keep the current `version` field and use 20 for HTTP/2?

My loosely held opinion is 1. No 2. Yes.

**Comment by programmer-ke** [comment]
So I'm new to the codebase but I've been doing a bit of research into this past few hours, came to report essentially what @pquentin has already brought up!

It does seem version is already set in `BaseHTTPResponse` when it is initialized as an integer.

https://github.com/programmer-ke/urllib3/blob/03f7b65a47d87036674a7909ca6c57d4b5cf1a81/src/urllib3/response.py#L332
https://github.com/programmer-ke/urllib3/blob/03f7b65a47d87036674a7909ca6c57d4b5cf1a81/src/urllib3/connection.py#L484
https://docs.python.org/3/library/http.client.html#http.client.HTTPResponse.version

**Comment by programmer-ke** [comment]
> Turns out `BaseHTTPResponse` already has a `version` field, which gets populated from `http.client.HTTPVersion.version`. It's an integer mapped from the [HTTP-version field](https://www.rfc-editor.org/rfc/rfc9112.html#name-http-version) in the start line. For example, `HTTP/1.1` is mapped to 11: https://github.com/python/cpython/blob/b822b85ac11e73bbe4417bf03ee770ab116bb42d/Lib/http/client.py#L342-L348.
> 
> While arguably more ugly than using the full string or even the [ALPN name](https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids), according to [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-protocol-version) it's OK to assume that a protocol will be two digits (major and minor), with the second digit being 0 if not specified.
> 
> Two decisions are needed here:
> 
>     1. Do we add a new `http_version` field and fill it with `HTTP/1.1` or `HTTP/2`?
> 
>     2. Do we keep the current `version` field and use 20 for HTTP/2?
> 
> 
> My loosely held opinion is 1. No 2. Yes.

This comment suggests that with emscripten, `_http_vsn_str` doesn't exist on the connection object. I'm not sure what the implications are when it comes to the version set in the `BaseHTTPResponse`. Maybe an edge case, but I'm not sure as I'm not familiar with the emscripten workings..

**Comment by illia-v** [comment]
> This comment suggests that with emscripten, `_http_vsn_str` doesn't exist on the connection object.
> 
> https://github.com/urllib3/urllib3/blob/03f7b65a47d87036674a7909ca6c57d4b5cf1a81/src/urllib3/connectionpool.py#L547
> 
> I'm not sure what the implications are when it comes to the version set in the `BaseHTTPResponse`. Maybe an edge case, but I'm not sure as I'm not familiar with the emscripten workings..

Yeah, `HTTP2Connection` is a subclass of `http.client.HTTPConnection`, and the latter hard-codes `_http_vsn_str = 'HTTP/1.1'` which we use for logging here.

https://github.com/urllib3/urllib3/blob/71e7c35662a4b2ba8543194cc132616065dfc56a/src/urllib3/connectionpool.py#L547-L560

cc @pquentin @sethmlarson
