### ISSUE TITLE
HTTPConnection.request chunked=False doesn't work properly

### ISSUE THREAD

**Issue by thinkjin99** [urllib3/urllib3#3379]
### Context

What are you trying to do?
How do you expect to do it?
Is it something you currently cannot do?
Is this related to an existing issue/problem?

Even when the chunk parameter is set to False, urllib3 still sends file data in chunks. 
It may seem natural for servers to use chunk encoding when there's no content-length, it can be confusing from the client's perspective.

To solve this, we might consider forcibly adding the content-length header when chunked is set to False. 
Or add new function to measure flie's content length and automatically add content-length header when chunking is disabled.

### Alternatives

Can you achieve the same result doing it in an alternative way?
Is the alternative considerable?

May be there could be other alternatives...

### Duplicate

Has the feature been requested before?
If so, please provide a link to the issue.

No

### Contribution

Would you be willing to submit a PR?
_(Help can be provided if you need assistance submitting a PR)_

yes

**Comment by sigmavirus24** [comment]
Please provide an example that can be used to reproduce the behavior you think you're seeing

**Comment by thinkjin99** [comment]
> Please provide an example that can be used to reproduce the behavior you think you're seeing

```python

body = open(
    "./test.png",
    "rb",
)

pool = urllib3.PoolManager()
res = pool.request("POST", url="http://127.0.0.1:80/files", body=body, chunked=False)
print(res.data)
```

you can reproduce it with this code. If you run this code urllib3 sends file data by chunking even chunked value is set False.

Also you can check it in test code 
```python
    @pytest.mark.parametrize("chunked", [True, False])
    @pytest.mark.parametrize("method", ["POST", "PUT", "PATCH"])
    @pytest.mark.parametrize("body_type", ["file", "generator", "bytes"])
    def test_chunked_specified(
        self, method: str, chunked: bool, body_type: str
    ) -> None:
        quit_event = threading.Event()
        buffer = bytearray()
        expected_bytes = b"\r\n\r\na\r\nxxxxxxxxxx\r\n0\r\n\r\n"
```


[link](https://github.com/urllib3/urllib3/blob/b7c2910a9f49ba0d58c8d4381500c208f9a24765/test/with_dummyserver/test_socketlevel.py#L2329C4-L2338C1)

If you look at the code you can check the body data is always set to be chunked whether chunked values is True or False

**Comment by sigmavirus24** [comment]
https://github.com/urllib3/urllib3/blob/b7c2910a9f49ba0d58c8d4381500c208f9a24765/test%2Fwith_dummyserver%2Ftest_socketlevel.py#L2368-L2380 this shows that in the case of a file or generator we disregard chunked being set. Which is desirable when you don't otherwise specify a content length. We can estimate the file size but we cannot guarantee that to be correct, thus the more correct thing is to never guess like you're asking us to. 

I believe you must specify your own content length for us to not chunk the transfer. You know what data you're sending better than we do.

**Comment by sigmavirus24** [comment]
https://github.com/urllib3/urllib3/blob/b7c2910a9f49ba0d58c8d4381500c208f9a24765/test%2Fwith_dummyserver%2Ftest_socketlevel.py#L2488-L2527 shows that if you send the content length header yourself then we don't chunk the request because you've specified how to frame the request. 

I'm inclined to decline your feature request here unless others disagree. 

Also, we cannot change this in a backwards compatible way as we're fundamentally changing the library's behavior that could potentially break how someone expects things to work

**Comment by thinkjin99** [comment]
As you said, 'I believe you must specify your own content length for us to not chunk the transfer. You know what data you're sending better than we do.' This implies that urllib3 would execute chunking if there is no given content-length.

So, it seems like chunking is the default behavior of the request function. Then, why is the default value of 'chunked' set to False? It's quite confusing..."

**Comment by thinkjin99** [comment]
I'm working in https://github.com/urllib3/urllib3/pull/3381

**Comment by sigmavirus24** [comment]
@thinkjin99 as I said, we can not change things to behave how you seem to expect. I don't understand what work you're doing

**Comment by thinkjin99** [comment]
I understand close this issue
