### ISSUE TITLE
Fix test_redirecting_to_bad_url failure in Requests

### ISSUE THREAD

**Issue by pquentin** [urllib3/urllib3#3392]
As part of our CI, we run the Requests test suite to make sure we don't accidentally break compatibility. The signal-to-noise ratio has been surprisingly high. That said, we are [currently seeing a failure](https://github.com/urllib3/urllib3/actions/runs/9036580373/job/24833736784?pr=3391) in `test_redirecting_to_bad_url`:

```python
_ TestPreparingURLs.test_redirecting_to_bad_url[http://localhost:-1-InvalidURL] _
self = <tests.test_requests.TestPreparingURLs object at 0x7fb1dde19be0>
httpbin = <function prepare_url.<locals>.inner at 0x7fb1dccd0ea0>
url = 'http://localhost:-1'
exception = <class 'requests.exceptions.InvalidURL'>
    @pytest.mark.parametrize("url, exception", (("http://localhost:-1", InvalidURL),))
    def test_redirecting_to_bad_url(self, httpbin, url, exception):
>       with pytest.raises(exception):
E       Failed: DID NOT RAISE <class 'requests.exceptions.InvalidURL'>
tests/test_requests.py:2726: Failed
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/urllib3/urllib3/.nox/downstream_requests/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/urllib3/urllib3/.nox/downstream_requests/lib/python3.12/site-packages/flask/app.py", line 1480, in wsgi_app
    return response(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/urllib3/urllib3/.nox/downstream_requests/lib/python3.12/site-packages/werkzeug/wrappers/response.py", line 576, in __call__
    app_iter, status, headers = self.get_wsgi_response(environ)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/urllib3/urllib3/.nox/downstream_requests/lib/python3.12/site-packages/werkzeug/wrappers/response.py", line 562, in get_wsgi_response
    headers = self.get_wsgi_headers(environ)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/urllib3/urllib3/.nox/downstream_requests/lib/python3.12/site-packages/werkzeug/wrappers/response.py", line 481, in get_wsgi_headers
    location = iri_to_uri(location)
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/urllib3/urllib3/.nox/downstream_requests/lib/python3.12/site-packages/werkzeug/urls.py", line 153, in iri_to_uri
    if parts.port:
       ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/urllib/parse.py", line 182, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as '-1'
127.0.0.1 - - [10/May/2024 18:36:31] "GET /redirect-to?url=http%3A%2F%2Flocalhost%3A-1 HTTP/1.1" 500 59
```

We should understand the issue, and then:

 * If it's an urllib3 issue, we should fix it.
 * If it's not, we should find where the issue is (requests, flask, werkzeug?), report the issue upstream and skip the test in urllib3.

**Comment by franekmagiera** [comment]
I've played around with it locally and can't quite find the change that caused this to stop working specifically, but here are my thoughts:
- this test in `requests` is quite simple really, it just calls httpbin's `redirect-to` [endpoint](https://httpbin.org/#/Redirects/get_redirect_to) with a `url=localhost:-1` param and it expects to get an `InvalidURL` exception
- when this test was passing, the exception was not caused on the client (urllib3/requests) side during the initial call to the httpbin (that is to the `redirect-to` endpoint), but I think it used to work like this:
    - `requests` would call the `redirect-to` endpoint
    - `httpbin` would respond with a `302` response
    - because `allow_redirects` is `True` by default, the client would try to call `localhost:-1`
    - now there would be an `InvalidURL` exception, because the port doesn't make sense
- now, I think something has changed in werkzeug/flask and instead of returning a `302` response initially, it returns a `500`, there is no redirect and the test fails - unfortuntely I haven't found the exact change that caused that behavior in flask/werkzeug

It seems to make sense to me, because when changing the test to 
```
@pytest.mark.parametrize("url, exception", (("http://localhost:-1", InvalidURL),))
    def test_redirecting_to_bad_url(self, httpbin, url, exception):
        with pytest.raises(exception):
            requests.get("https://httpbin.org/redirect-to", params={"url": url})
```
it passes again. I suspect this is because the real server still uses the old version of flask/werkzeug and `requests`' test suite uses `pytest-httpbin` which probably uses the new version of flask/werkzeug.

That said, there are two more things:
- I feel like it'd be worth to rewrite this test. It relies on the fact that the redirect will happen, which is dependant on the behavior of the third party library. Not the easiest setup to understand. Initially, I was under the impression, that the initial call should raise an exception, but it doesn't make sense really, because you can't verify the query params reliably (unless you know how this specific endpoint behaves). It feels to me that testing that just running `get('localhost:-1')` should raise the exception, plus that when `allow_redirects=True` the client tries to follow the next call. Maybe it'd be worth considering writing a test with a dummy server that would return `302` with a wrong URI in the `Location` header.
- It'd be worth to highlight this to the flask/werkzeug maintainers, probably they don't want to return `500` if someone tries to put something weird in the `Location` header, but I'd need more information, because right now those are only my suspicions.

I might take another look at this tomorrow.

**Comment by sigmavirus24** [comment]
To be clear @franekmagiera you're saying that the difference is between asking it to send us a redirect to:

* `localhost:-1`
* `http://localhost:-1`

Is that right? The difference is that the scheme was added in what succeeded for you? If so, then this is definitely a bug in Flask/werkzeug. Redirects can be any of the following:

* Full URI (or `{scheme}://{authority}[/{path}[?{query}[#{fragment}]]]`) e.g., `http://example.com:80/test?1=1#anchor`, `http://example.com/#anchor`, `https://example.com:443/?q=1`, `https://example.com/test`
* scheme-less (or `//{authority}[/{path}[?{query}[#{fragment}]]]`)
* scheme- & authority-less (or `[/]{path}[?{query}][#{fragment}]`)

What you might be wondering though is why is this still a bug:

As far as handling a URL is concerned, technically even though Requests was asking for something wrong (what I believe it wanted was `//localhost:-1`) a path can be a relative-path redirect. So Flask and urllib3/Requests should have treated that as:

```
HTTP/1.1 302 Found
...
Location: localhost%3A-1
```

Which should have resulted in a request to:

```
https://httpbin.org/redirect-to/localhost%3A-1
```

So, if Flask/werkzeug is having an issue dealing with that redirect, we need a minimal reproducer for them.

We also need a patch for Requests. I suspect what was wanted in that test was `//localhost:-1` which should be returned to us as 


```
HTTP/1.1 302 Found
...
Location: //localhost:-1
```

And result in

```
https://localhost:-1
```

After resolving the URI with the original request-host.

**Comment by franekmagiera** [comment]
> you're saying that the difference is between asking it to send us a redirect to:
> - `localhost:-1`
> - `http://localhost:-1`

No, I suspect the difference is calling real `httpbin` vs using `pytest-httpbin` (which as far as I know spins up a local httpbin server). I think before it would work like this:
1. Requests sends a request to the `redirect-to` endpoint.
2. httpbin happily returns a `302` response with `Location: localhost:-1` (I'm not sure the encoding is right but it doesn't matter for the explanation).
3. Requests tries to reach the host from the redirect, which supposedly listens on port `-1`.
4. Requests/urllib3 throw an exception, because of the `-1` port.
5. The test passes, because the "expected exception" is thrown.

I think now it behaves like:
1. Requests sends a request to the `redirect-to` endpoint.
2. httpbin returns a `500` response
3. The test fails because no exeception is thrown

**Comment by sigmavirus24** [comment]
Is the initial request returning a 500, or is the request after the redirect returning a 500 because those are different and I suspect it to be the latter and I know why it would be the case. Is there a stack trace or anything other than what you have here explaining the behavior? I can't get to a computer this weekend to debug this

**Comment by franekmagiera** [comment]
Yes, the initial request is returning a 500 ([ci logs](https://github.com/urllib3/urllib3/actions/runs/9036580373/job/24833736784?pr=3391#step:5:304))

**Comment by sigmavirus24** [comment]
Ah, I missed that on my phone. I see the problem now

**Comment by zawan-ila** [comment]
I suspect this is due to https://github.com/pallets/werkzeug/pull/2894. Earlier, "ascii" locations would not be processed through the `iri_to_uri` method but now they are.

**Comment by franekmagiera** [comment]
Yeah, and then somehow it fails in standard urllib, but I couldn't quite figure out the exact line that executes that now.

Anyway, I feel quite confident that the explanation above is correct. If that's true, this test will probably fail in `requests` CI as well. There are a couple of issues:
- do we want to fix this in the `requests` project? I could try to change the testing approach as explained in the previous post so that validating this behavior does not depend on the behavior of httpbin, but not sure if I'd have time this week
- Maybe werkzeug should just throw a different exception explicitly (something like "Wrong port number put into the `Location` header). I'd need to verify in HTTP spec if a server could respond with a `302` with a wrong URI in the `Location` header.
- I'd say given [this comment](https://github.com/postmanlabs/httpbin/blob/master/httpbin/core.py#L634) this change broke httpbin's contract. Not sure if it's still maintained though. And given the point above, not sure if it's expected to be able to put whatever in the `Location` header.

**Comment by franekmagiera** [comment]
Ah, okay, now I get it. It is because `parts` is a [return value from urllib's urlsplit function](https://github.com/pallets/werkzeug/pull/2894/files#diff-342c3ac7878fc8165fb66b641c3a05ae0b4e5da5c9273fd00db272d61422bb89L84), and `parts.port` is a `@property` that executes [this](https://github.com/python/cpython/blob/main/Lib/urllib/parse.py#L176) and `"-1".isdigit()` returns `False` which then raises the exception.

**Comment by sigmavirus24** [comment]
> Not sure if it's still maintained though

It's maintained at psf/httpbin

**Comment by franekmagiera** [comment]
Let me know if you would be happy accepting something like this https://github.com/psf/requests/pull/6700 (1 line change)

**Comment by pquentin** [comment]
Thanks @franekmagiera for the fix, thanks @sigmavirus24 for the help (including merging the requests fix) and @zawan-ila for te tip.

@franekmagiera While you can continue investigating if you want and fix other things, as far as urllib3 is concerned, the issue is fixed as the CI is green again: https://github.com/urllib3/urllib3/actions/runs/9058498782/job/24884236239. I'll go ahead and close the issue, and you can claim the bounty on Open Collective.
