### ISSUE TITLE
Add support for HTTP/2 chunked request bodies

### ISSUE THREAD

**Issue by sethmlarson** [urllib3/urllib3#3425]
HTTP/2 doesn't support the `Transfer-Encoding: chunked` header because it doesn't need the header or additional framing, instead relying on the stream framing mechanism. If users send a request with `chunked=True` we should not emit the above mentioned header and send the request body without the additional framing.

**Comment by zawan-ila** [comment]
@sethmlarson Looking at the code, I think that we already [ignore](https://github.com/urllib3/urllib3/blob/main/src/urllib3/http2.py#L267-L270) the `chunked` kwarg and do not emit the `Transfer-Encoding` header. This implies that there is no need for this task?

Looking at the discussion [here](https://github.com/urllib3/urllib3/pull/3421#discussion_r1666195312), maybe the goal is to raise an exception if chunked encoding is requested? In that case, could you have a look at [PR-3429](https://github.com/urllib3/urllib3/pull/3429). It's in draft right now since I am not sure if it's indeed what's needed here.
