### ISSUE TITLE
urllib3 does not provide a way to send full chain-of-trust when server makes a CertificateRequest 

### ISSUE THREAD

**Issue by jaloren** [urllib3/urllib3#878]
I am on python2.7 installed on CentOS 6. I have OpenSSL 1.0.1e. I have requests version 2.9.1. The HTTP server is performing SSL client authentication. The client's chain has a verification depth of 2, which means there's a single intermediate CA certificate in the client chain. I am not sure if this is a bug or a feature request.

Based on the public api, I sent a request in like so. note i have explicitly chosen not to verify the server's chain of trust (i know that's not secure but this isn't being used in production). The cert.pem contains the client's PEM-encoded certificate, the intermediate CA cert, and the root cert. The final entity in the cert.pem is the client's private key (which is NOT encrypted).

resp = requests.get(url,verify=False,cert='cert.pem')

The following exception is thrown.

requests.exceptions.SSLError: Errno bad handshake

Looking at the server's ssl logs, I can see that the reason the server terminated the SSL connection was caused by the server's inability to construct the client's chain-of-trust. The server could not do this because the request's library only sent its client cert in it. I used openssl s_server to verify this as well.

I could not find anything in the official documentation that would allow me to specify a set of certs to be included in the client's chain-of-trust.

Looking at the pyopenssl wrapper used by requests, I can see the Context.use_certificate method, which sets the leaf cert. I am suspecting that only sets a single certificate. I suspect that for this to work, the requests external api would need to provide an interface for passing in a list of PEM-encoded certs, which is then set via the Context.add_extra_chain_cert method.
##

**Comment by Lukasa** [comment]
Thanks for this @jaloren!

So it looks to me at first blush as though this problem exists only when using PyOpenSSL. When using the stdlib, urllib3 calls load_cert_chain for the client certs, which AFAIK should work as expected, but the PyOpenSSL wrapper doesn't do the same thing (though I'd like it if @tiran would double-check that for me).

It sounds like the thing to do is to swap PyOpenSSL to use `use_certificate_chain_file` or something like it. However, I'd like to hold off on doing that until we can get #835 merged, because that will give us a single unified place to make the change in a way that will be really clear.

Is that ok with everyone?

**Comment by haikuginger** [comment]
That sounds good to me @Lukasa; once support for SSL contexts gets merged, we may want to look into figuring out exactly where PyOpenSSL behavior differs from the stdlib and bringing them into parity where possible.

**Comment by pquentin** [comment]
I believe this bug got fixed in #1246 and can now be closed.

**Comment by pquentin** [comment]
Or maybe there's something else to do here?

**Comment by SethMichaelLarson** [comment]
This looks closable from that PR, if more needs to be done we'll reopen. Thanks @pquentin!
