### ISSUE TITLE
Proxy handling like urllib2

### ISSUE THREAD

**Issue by viyatb** [urllib3/urllib3#886]
The `ProxyHandler` in urllib2 uses a dictionary of proxies for http and https connections. Like

`urllib2.ProxyHandler({'http': 'http://proxy', 'https': 'https://proxy'})`.

Is there any such support here? There is no such mention in the documentation.
##

**Comment by Lukasa** [comment]
@delta24 There is not: you'd use one `ProxyManager` per proxy.

@shazow we could implement this at the `SessionManager` level, I suppose...

**Comment by haikuginger** [comment]
If we're putting it anywhere, then I'd agree `SessionManager` makes sense. I'm not sure, though.

We could, instead of directly accessing the `PoolManager` we instantiate it with, have `SessionManager` call `self.get_pool_manager()` or similar; users could subclass `SessionManager`, instantiate however many `ProxyManager` objects they want, and override that method so that it's picking the relevant manager each time. Not sure if it's in the remit of `SessionManager` to have that logic natively, but we could certainly provide a recipe.

**Comment by Lukasa** [comment]
I definitely feel *super* lukewarm about the idea of providing this functionality. It really does seem to amount to being about 5 lines of user code, and not particularly complex code either.

**Comment by shazow** [comment]
Sounds like we can start with a recipe in the docs and maybe improve it in the future?

Can anyone explain when it makes sense to use separate HTTP and HTTPS proxies?

**Comment by sethmlarson** [comment]
Since SessionManager isn't being worked on currently we're going to decline this for now.
